// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/proto/server-events.proto

// Protobuf Java Version: 3.25.0
package com.beverly.hills.money.gang.dto;

public final class ServerEventsOuterClass {
  private ServerEventsOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_daikombat_ServerEvents_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_daikombat_ServerEvents_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_daikombat_ServerEvents_ChatEvents_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_daikombat_ServerEvents_ChatEvents_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_daikombat_ServerEvents_GameEvents_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_daikombat_ServerEvents_GameEvents_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_daikombat_ServerEvents_ChatEvent_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_daikombat_ServerEvents_ChatEvent_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_daikombat_ServerEvents_GameEvent_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_daikombat_ServerEvents_GameEvent_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_daikombat_ServerEvents_GameEvent_Vector_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_daikombat_ServerEvents_GameEvent_Vector_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n,src/main/resources/proto/server-events" +
      ".proto\022\tdaikombat\"\310\005\n\014ServerEvents\022\017\n\007ev" +
      "entId\030\001 \001(\005\022\025\n\rplayersOnline\030\002 \001(\005\022\021\n\004hm" +
      "ac\030\003 \001(\005H\001\210\001\001\0227\n\nchatEvents\030\004 \001(\0132!.daik" +
      "ombat.ServerEvents.ChatEventH\000\0228\n\ngameEv" +
      "ents\030\005 \001(\0132\".daikombat.ServerEvents.Game" +
      "EventsH\000\032?\n\nChatEvents\0221\n\006events\030\001 \003(\0132!" +
      ".daikombat.ServerEvents.ChatEvent\032?\n\nGam" +
      "eEvents\0221\n\006events\030\001 \003(\0132!.daikombat.Serv" +
      "erEvents.GameEvent\0320\n\tChatEvent\022\022\n\nplaye" +
      "rName\030\001 \001(\t\022\017\n\007message\030\002 \001(\t\032\302\002\n\tGameEve" +
      "nt\022B\n\teventType\030\001 \001(\0162/.daikombat.Server" +
      "Events.GameEvent.GameEventType\022:\n\010positi" +
      "on\030\002 \001(\0132(.daikombat.ServerEvents.GameEv" +
      "ent.Vector\022;\n\tdirection\030\003 \001(\0132(.daikomba" +
      "t.ServerEvents.GameEvent.Vector\032\036\n\006Vecto" +
      "r\022\t\n\001x\030\001 \001(\002\022\t\n\001y\030\002 \001(\002\"X\n\rGameEventType" +
      "\022\010\n\004MOVE\020\000\022\t\n\005SHOOT\020\001\022\014\n\010GET_SHOT\020\002\022\t\n\005D" +
      "EATH\020\003\022\t\n\005SPAWN\020\004\022\016\n\nDISCONNECT\020\005B\010\n\006eve" +
      "ntsB\007\n\005_hmacB$\n com.beverly.hills.money." +
      "gang.dtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_daikombat_ServerEvents_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_daikombat_ServerEvents_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_daikombat_ServerEvents_descriptor,
        new java.lang.String[] { "EventId", "PlayersOnline", "Hmac", "ChatEvents", "GameEvents", "Events", });
    internal_static_daikombat_ServerEvents_ChatEvents_descriptor =
      internal_static_daikombat_ServerEvents_descriptor.getNestedTypes().get(0);
    internal_static_daikombat_ServerEvents_ChatEvents_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_daikombat_ServerEvents_ChatEvents_descriptor,
        new java.lang.String[] { "Events", });
    internal_static_daikombat_ServerEvents_GameEvents_descriptor =
      internal_static_daikombat_ServerEvents_descriptor.getNestedTypes().get(1);
    internal_static_daikombat_ServerEvents_GameEvents_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_daikombat_ServerEvents_GameEvents_descriptor,
        new java.lang.String[] { "Events", });
    internal_static_daikombat_ServerEvents_ChatEvent_descriptor =
      internal_static_daikombat_ServerEvents_descriptor.getNestedTypes().get(2);
    internal_static_daikombat_ServerEvents_ChatEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_daikombat_ServerEvents_ChatEvent_descriptor,
        new java.lang.String[] { "PlayerName", "Message", });
    internal_static_daikombat_ServerEvents_GameEvent_descriptor =
      internal_static_daikombat_ServerEvents_descriptor.getNestedTypes().get(3);
    internal_static_daikombat_ServerEvents_GameEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_daikombat_ServerEvents_GameEvent_descriptor,
        new java.lang.String[] { "EventType", "Position", "Direction", });
    internal_static_daikombat_ServerEvents_GameEvent_Vector_descriptor =
      internal_static_daikombat_ServerEvents_GameEvent_descriptor.getNestedTypes().get(0);
    internal_static_daikombat_ServerEvents_GameEvent_Vector_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_daikombat_ServerEvents_GameEvent_Vector_descriptor,
        new java.lang.String[] { "X", "Y", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
