package com.beverly.hills.money.gang.exception;

public enum GameErrorCode {
  COMMON_ERROR,
  AUTH_ERROR,
  PLAYER_EXISTS,
  SERVER_FULL,
  NOT_EXISTING_GAME_ROOM,
  COMMAND_NOT_RECOGNIZED,
  CAN_NOT_ATTACK_YOURSELF,
  GAME_CLOSED,
  CHEATING,
  PLAYER_DOES_NOT_EXIST,

}
