// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: schema/src/main/resources/server-command.proto

// Protobuf Java Version: 3.25.0
package com.beverly.hills.money.gang.proto;

public interface DownloadMapAssetsCommandOrBuilder extends
    // @@protoc_insertion_point(interface_extends:daikombat.dto.DownloadMapAssetsCommand)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string mapName = 1;</code>
   * @return Whether the mapName field is set.
   */
  boolean hasMapName();
  /**
   * <code>optional string mapName = 1;</code>
   * @return The mapName.
   */
  java.lang.String getMapName();
  /**
   * <code>optional string mapName = 1;</code>
   * @return The bytes for mapName.
   */
  com.google.protobuf.ByteString
      getMapNameBytes();
}
