// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: schema/src/main/resources/server-command.proto

// Protobuf Java Version: 3.25.0
package com.beverly.hills.money.gang.proto;

public interface JoinGameCommandOrBuilder extends
    // @@protoc_insertion_point(interface_extends:daikombat.dto.JoinGameCommand)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 gameId = 1;</code>
   * @return The gameId.
   */
  int getGameId();

  /**
   * <code>string playerName = 3;</code>
   * @return The playerName.
   */
  java.lang.String getPlayerName();
  /**
   * <code>string playerName = 3;</code>
   * @return The bytes for playerName.
   */
  com.google.protobuf.ByteString
      getPlayerNameBytes();
}
