// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: schema/src/main/resources/server-common.proto

// Protobuf Java Version: 3.25.0
package com.beverly.hills.money.gang.proto;

public interface MapAssetsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:daikombat.dto.MapAssets)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional bytes atlasPng = 1;</code>
   * @return Whether the atlasPng field is set.
   */
  boolean hasAtlasPng();
  /**
   * <code>optional bytes atlasPng = 1;</code>
   * @return The atlasPng.
   */
  com.google.protobuf.ByteString getAtlasPng();

  /**
   * <code>optional bytes atlasTsx = 2;</code>
   * @return Whether the atlasTsx field is set.
   */
  boolean hasAtlasTsx();
  /**
   * <code>optional bytes atlasTsx = 2;</code>
   * @return The atlasTsx.
   */
  com.google.protobuf.ByteString getAtlasTsx();

  /**
   * <code>optional bytes onlineMapTmx = 3;</code>
   * @return Whether the onlineMapTmx field is set.
   */
  boolean hasOnlineMapTmx();
  /**
   * <code>optional bytes onlineMapTmx = 3;</code>
   * @return The onlineMapTmx.
   */
  com.google.protobuf.ByteString getOnlineMapTmx();
}
