// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: schema/src/main/resources/server-common.proto

// Protobuf Java Version: 3.25.0
package com.beverly.hills.money.gang.proto;

/**
 * Protobuf enum {@code daikombat.dto.PlayerSkinColor}
 */
public enum PlayerSkinColor
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>GREEN = 0;</code>
   */
  GREEN(0),
  /**
   * <code>PINK = 1;</code>
   */
  PINK(1),
  /**
   * <code>PURPLE = 2;</code>
   */
  PURPLE(2),
  /**
   * <code>BLUE = 3;</code>
   */
  BLUE(3),
  /**
   * <code>YELLOW = 4;</code>
   */
  YELLOW(4),
  /**
   * <code>ORANGE = 5;</code>
   */
  ORANGE(5),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>GREEN = 0;</code>
   */
  public static final int GREEN_VALUE = 0;
  /**
   * <code>PINK = 1;</code>
   */
  public static final int PINK_VALUE = 1;
  /**
   * <code>PURPLE = 2;</code>
   */
  public static final int PURPLE_VALUE = 2;
  /**
   * <code>BLUE = 3;</code>
   */
  public static final int BLUE_VALUE = 3;
  /**
   * <code>YELLOW = 4;</code>
   */
  public static final int YELLOW_VALUE = 4;
  /**
   * <code>ORANGE = 5;</code>
   */
  public static final int ORANGE_VALUE = 5;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static PlayerSkinColor valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static PlayerSkinColor forNumber(int value) {
    switch (value) {
      case 0: return GREEN;
      case 1: return PINK;
      case 2: return PURPLE;
      case 3: return BLUE;
      case 4: return YELLOW;
      case 5: return ORANGE;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<PlayerSkinColor>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      PlayerSkinColor> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<PlayerSkinColor>() {
          public PlayerSkinColor findValueByNumber(int number) {
            return PlayerSkinColor.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.beverly.hills.money.gang.proto.ServerCommon.getDescriptor().getEnumTypes().get(1);
  }

  private static final PlayerSkinColor[] VALUES = values();

  public static PlayerSkinColor valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private PlayerSkinColor(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:daikombat.dto.PlayerSkinColor)
}

