// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: schema/src/main/resources/server-command.proto

// Protobuf Java Version: 3.25.0
package com.beverly.hills.money.gang.proto;

/**
 * Protobuf enum {@code daikombat.dto.PlayerClass}
 */
public enum PlayerClass
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>COMMONER = 0;</code>
   */
  COMMONER(0),
  /**
   * <code>DRACULA_BERSERK = 1;</code>
   */
  DRACULA_BERSERK(1),
  /**
   * <code>DEMON_TANK = 2;</code>
   */
  DEMON_TANK(2),
  /**
   * <code>BEAST_WARRIOR = 3;</code>
   */
  BEAST_WARRIOR(3),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>COMMONER = 0;</code>
   */
  public static final int COMMONER_VALUE = 0;
  /**
   * <code>DRACULA_BERSERK = 1;</code>
   */
  public static final int DRACULA_BERSERK_VALUE = 1;
  /**
   * <code>DEMON_TANK = 2;</code>
   */
  public static final int DEMON_TANK_VALUE = 2;
  /**
   * <code>BEAST_WARRIOR = 3;</code>
   */
  public static final int BEAST_WARRIOR_VALUE = 3;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static PlayerClass valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static PlayerClass forNumber(int value) {
    switch (value) {
      case 0: return COMMONER;
      case 1: return DRACULA_BERSERK;
      case 2: return DEMON_TANK;
      case 3: return BEAST_WARRIOR;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<PlayerClass>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      PlayerClass> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<PlayerClass>() {
          public PlayerClass findValueByNumber(int number) {
            return PlayerClass.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.beverly.hills.money.gang.proto.ServerCommandOuterClass.getDescriptor().getEnumTypes().get(1);
  }

  private static final PlayerClass[] VALUES = values();

  public static PlayerClass valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private PlayerClass(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:daikombat.dto.PlayerClass)
}

