// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: schema/src/main/resources/server-command.proto

// Protobuf Java Version: 3.25.0
package com.beverly.hills.money.gang.proto;

public interface PushChatEventCommandOrBuilder extends
    // @@protoc_insertion_point(interface_extends:daikombat.dto.PushChatEventCommand)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 gameId = 1;</code>
   * @return The gameId.
   */
  int getGameId();

  /**
   * <code>string message = 2;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 2;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <code>int32 playerId = 3;</code>
   * @return The playerId.
   */
  int getPlayerId();
}
