// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: schema/src/main/resources/server-command.proto

// Protobuf Java Version: 3.25.0
package com.beverly.hills.money.gang.proto;

public interface PushChatEventCommandOrBuilder extends
    // @@protoc_insertion_point(interface_extends:daikombat.dto.PushChatEventCommand)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int32 gameId = 1;</code>
   * @return Whether the gameId field is set.
   */
  boolean hasGameId();
  /**
   * <code>optional int32 gameId = 1;</code>
   * @return The gameId.
   */
  int getGameId();

  /**
   * <code>optional string message = 2;</code>
   * @return Whether the message field is set.
   */
  boolean hasMessage();
  /**
   * <code>optional string message = 2;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>optional string message = 2;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <code>optional int32 playerId = 3;</code>
   * @return Whether the playerId field is set.
   */
  boolean hasPlayerId();
  /**
   * <code>optional int32 playerId = 3;</code>
   * @return The playerId.
   */
  int getPlayerId();

  /**
   * <code>optional .daikombat.dto.Taunt taunt = 4;</code>
   * @return Whether the taunt field is set.
   */
  boolean hasTaunt();
  /**
   * <code>optional .daikombat.dto.Taunt taunt = 4;</code>
   * @return The enum numeric value on the wire for taunt.
   */
  int getTauntValue();
  /**
   * <code>optional .daikombat.dto.Taunt taunt = 4;</code>
   * @return The taunt.
   */
  com.beverly.hills.money.gang.proto.Taunt getTaunt();
}
