// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: schema/src/main/resources/server-command.proto

// Protobuf Java Version: 3.25.0
package com.beverly.hills.money.gang.proto;

/**
 * Protobuf type {@code daikombat.dto.PushGameEventCommand}
 */
public final class PushGameEventCommand extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:daikombat.dto.PushGameEventCommand)
    PushGameEventCommandOrBuilder {
private static final long serialVersionUID = 0L;
  // Use PushGameEventCommand.newBuilder() to construct.
  private PushGameEventCommand(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private PushGameEventCommand() {
    eventType_ = 0;
    weaponType_ = 0;
    powerUp_ = 0;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new PushGameEventCommand();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.beverly.hills.money.gang.proto.ServerCommandOuterClass.internal_static_daikombat_dto_PushGameEventCommand_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.beverly.hills.money.gang.proto.ServerCommandOuterClass.internal_static_daikombat_dto_PushGameEventCommand_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.beverly.hills.money.gang.proto.PushGameEventCommand.class, com.beverly.hills.money.gang.proto.PushGameEventCommand.Builder.class);
  }

  /**
   * Protobuf enum {@code daikombat.dto.PushGameEventCommand.GameEventType}
   */
  public enum GameEventType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>MOVE = 0;</code>
     */
    MOVE(0),
    /**
     * <code>ATTACK = 1;</code>
     */
    ATTACK(1),
    /**
     * <code>POWER_UP_PICKUP = 2;</code>
     */
    POWER_UP_PICKUP(2),
    /**
     * <code>TELEPORT = 3;</code>
     */
    TELEPORT(3),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>MOVE = 0;</code>
     */
    public static final int MOVE_VALUE = 0;
    /**
     * <code>ATTACK = 1;</code>
     */
    public static final int ATTACK_VALUE = 1;
    /**
     * <code>POWER_UP_PICKUP = 2;</code>
     */
    public static final int POWER_UP_PICKUP_VALUE = 2;
    /**
     * <code>TELEPORT = 3;</code>
     */
    public static final int TELEPORT_VALUE = 3;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static GameEventType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static GameEventType forNumber(int value) {
      switch (value) {
        case 0: return MOVE;
        case 1: return ATTACK;
        case 2: return POWER_UP_PICKUP;
        case 3: return TELEPORT;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<GameEventType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        GameEventType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<GameEventType>() {
            public GameEventType findValueByNumber(int number) {
              return GameEventType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.beverly.hills.money.gang.proto.PushGameEventCommand.getDescriptor().getEnumTypes().get(0);
    }

    private static final GameEventType[] VALUES = values();

    public static GameEventType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private GameEventType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:daikombat.dto.PushGameEventCommand.GameEventType)
  }

  private int bitField0_;
  public static final int GAMEID_FIELD_NUMBER = 1;
  private int gameId_ = 0;
  /**
   * <code>optional int32 gameId = 1;</code>
   * @return Whether the gameId field is set.
   */
  @java.lang.Override
  public boolean hasGameId() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional int32 gameId = 1;</code>
   * @return The gameId.
   */
  @java.lang.Override
  public int getGameId() {
    return gameId_;
  }

  public static final int EVENTTYPE_FIELD_NUMBER = 2;
  private int eventType_ = 0;
  /**
   * <code>optional .daikombat.dto.PushGameEventCommand.GameEventType eventType = 2;</code>
   * @return Whether the eventType field is set.
   */
  @java.lang.Override public boolean hasEventType() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>optional .daikombat.dto.PushGameEventCommand.GameEventType eventType = 2;</code>
   * @return The enum numeric value on the wire for eventType.
   */
  @java.lang.Override public int getEventTypeValue() {
    return eventType_;
  }
  /**
   * <code>optional .daikombat.dto.PushGameEventCommand.GameEventType eventType = 2;</code>
   * @return The eventType.
   */
  @java.lang.Override public com.beverly.hills.money.gang.proto.PushGameEventCommand.GameEventType getEventType() {
    com.beverly.hills.money.gang.proto.PushGameEventCommand.GameEventType result = com.beverly.hills.money.gang.proto.PushGameEventCommand.GameEventType.forNumber(eventType_);
    return result == null ? com.beverly.hills.money.gang.proto.PushGameEventCommand.GameEventType.UNRECOGNIZED : result;
  }

  public static final int POSITION_FIELD_NUMBER = 3;
  private com.beverly.hills.money.gang.proto.Vector position_;
  /**
   * <code>optional .daikombat.dto.Vector position = 3;</code>
   * @return Whether the position field is set.
   */
  @java.lang.Override
  public boolean hasPosition() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>optional .daikombat.dto.Vector position = 3;</code>
   * @return The position.
   */
  @java.lang.Override
  public com.beverly.hills.money.gang.proto.Vector getPosition() {
    return position_ == null ? com.beverly.hills.money.gang.proto.Vector.getDefaultInstance() : position_;
  }
  /**
   * <code>optional .daikombat.dto.Vector position = 3;</code>
   */
  @java.lang.Override
  public com.beverly.hills.money.gang.proto.VectorOrBuilder getPositionOrBuilder() {
    return position_ == null ? com.beverly.hills.money.gang.proto.Vector.getDefaultInstance() : position_;
  }

  public static final int DIRECTION_FIELD_NUMBER = 4;
  private com.beverly.hills.money.gang.proto.Vector direction_;
  /**
   * <code>optional .daikombat.dto.Vector direction = 4;</code>
   * @return Whether the direction field is set.
   */
  @java.lang.Override
  public boolean hasDirection() {
    return ((bitField0_ & 0x00000008) != 0);
  }
  /**
   * <code>optional .daikombat.dto.Vector direction = 4;</code>
   * @return The direction.
   */
  @java.lang.Override
  public com.beverly.hills.money.gang.proto.Vector getDirection() {
    return direction_ == null ? com.beverly.hills.money.gang.proto.Vector.getDefaultInstance() : direction_;
  }
  /**
   * <code>optional .daikombat.dto.Vector direction = 4;</code>
   */
  @java.lang.Override
  public com.beverly.hills.money.gang.proto.VectorOrBuilder getDirectionOrBuilder() {
    return direction_ == null ? com.beverly.hills.money.gang.proto.Vector.getDefaultInstance() : direction_;
  }

  public static final int PLAYERID_FIELD_NUMBER = 5;
  private int playerId_ = 0;
  /**
   * <code>optional int32 playerId = 5;</code>
   * @return Whether the playerId field is set.
   */
  @java.lang.Override
  public boolean hasPlayerId() {
    return ((bitField0_ & 0x00000010) != 0);
  }
  /**
   * <code>optional int32 playerId = 5;</code>
   * @return The playerId.
   */
  @java.lang.Override
  public int getPlayerId() {
    return playerId_;
  }

  public static final int AFFECTEDPLAYERID_FIELD_NUMBER = 6;
  private int affectedPlayerId_ = 0;
  /**
   * <code>optional int32 affectedPlayerId = 6;</code>
   * @return Whether the affectedPlayerId field is set.
   */
  @java.lang.Override
  public boolean hasAffectedPlayerId() {
    return ((bitField0_ & 0x00000020) != 0);
  }
  /**
   * <code>optional int32 affectedPlayerId = 6;</code>
   * @return The affectedPlayerId.
   */
  @java.lang.Override
  public int getAffectedPlayerId() {
    return affectedPlayerId_;
  }

  public static final int SEQUENCE_FIELD_NUMBER = 7;
  private int sequence_ = 0;
  /**
   * <code>optional int32 sequence = 7;</code>
   * @return Whether the sequence field is set.
   */
  @java.lang.Override
  public boolean hasSequence() {
    return ((bitField0_ & 0x00000040) != 0);
  }
  /**
   * <code>optional int32 sequence = 7;</code>
   * @return The sequence.
   */
  @java.lang.Override
  public int getSequence() {
    return sequence_;
  }

  public static final int PINGMLS_FIELD_NUMBER = 8;
  private int pingMls_ = 0;
  /**
   * <code>optional int32 pingMls = 8;</code>
   * @return Whether the pingMls field is set.
   */
  @java.lang.Override
  public boolean hasPingMls() {
    return ((bitField0_ & 0x00000080) != 0);
  }
  /**
   * <code>optional int32 pingMls = 8;</code>
   * @return The pingMls.
   */
  @java.lang.Override
  public int getPingMls() {
    return pingMls_;
  }

  public static final int TELEPORTID_FIELD_NUMBER = 9;
  private int teleportId_ = 0;
  /**
   * <code>optional int32 teleportId = 9;</code>
   * @return Whether the teleportId field is set.
   */
  @java.lang.Override
  public boolean hasTeleportId() {
    return ((bitField0_ & 0x00000100) != 0);
  }
  /**
   * <code>optional int32 teleportId = 9;</code>
   * @return The teleportId.
   */
  @java.lang.Override
  public int getTeleportId() {
    return teleportId_;
  }

  public static final int WEAPONTYPE_FIELD_NUMBER = 10;
  private int weaponType_ = 0;
  /**
   * <code>optional .daikombat.dto.WeaponType weaponType = 10;</code>
   * @return Whether the weaponType field is set.
   */
  @java.lang.Override public boolean hasWeaponType() {
    return ((bitField0_ & 0x00000200) != 0);
  }
  /**
   * <code>optional .daikombat.dto.WeaponType weaponType = 10;</code>
   * @return The enum numeric value on the wire for weaponType.
   */
  @java.lang.Override public int getWeaponTypeValue() {
    return weaponType_;
  }
  /**
   * <code>optional .daikombat.dto.WeaponType weaponType = 10;</code>
   * @return The weaponType.
   */
  @java.lang.Override public com.beverly.hills.money.gang.proto.WeaponType getWeaponType() {
    com.beverly.hills.money.gang.proto.WeaponType result = com.beverly.hills.money.gang.proto.WeaponType.forNumber(weaponType_);
    return result == null ? com.beverly.hills.money.gang.proto.WeaponType.UNRECOGNIZED : result;
  }

  public static final int PROJECTILE_FIELD_NUMBER = 11;
  private com.beverly.hills.money.gang.proto.ProjectileCoordinates projectile_;
  /**
   * <code>optional .daikombat.dto.ProjectileCoordinates projectile = 11;</code>
   * @return Whether the projectile field is set.
   */
  @java.lang.Override
  public boolean hasProjectile() {
    return ((bitField0_ & 0x00000400) != 0);
  }
  /**
   * <code>optional .daikombat.dto.ProjectileCoordinates projectile = 11;</code>
   * @return The projectile.
   */
  @java.lang.Override
  public com.beverly.hills.money.gang.proto.ProjectileCoordinates getProjectile() {
    return projectile_ == null ? com.beverly.hills.money.gang.proto.ProjectileCoordinates.getDefaultInstance() : projectile_;
  }
  /**
   * <code>optional .daikombat.dto.ProjectileCoordinates projectile = 11;</code>
   */
  @java.lang.Override
  public com.beverly.hills.money.gang.proto.ProjectileCoordinatesOrBuilder getProjectileOrBuilder() {
    return projectile_ == null ? com.beverly.hills.money.gang.proto.ProjectileCoordinates.getDefaultInstance() : projectile_;
  }

  public static final int POWERUP_FIELD_NUMBER = 12;
  private int powerUp_ = 0;
  /**
   * <code>optional .daikombat.dto.GamePowerUpType powerUp = 12;</code>
   * @return Whether the powerUp field is set.
   */
  @java.lang.Override public boolean hasPowerUp() {
    return ((bitField0_ & 0x00000800) != 0);
  }
  /**
   * <code>optional .daikombat.dto.GamePowerUpType powerUp = 12;</code>
   * @return The enum numeric value on the wire for powerUp.
   */
  @java.lang.Override public int getPowerUpValue() {
    return powerUp_;
  }
  /**
   * <code>optional .daikombat.dto.GamePowerUpType powerUp = 12;</code>
   * @return The powerUp.
   */
  @java.lang.Override public com.beverly.hills.money.gang.proto.GamePowerUpType getPowerUp() {
    com.beverly.hills.money.gang.proto.GamePowerUpType result = com.beverly.hills.money.gang.proto.GamePowerUpType.forNumber(powerUp_);
    return result == null ? com.beverly.hills.money.gang.proto.GamePowerUpType.UNRECOGNIZED : result;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeInt32(1, gameId_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeEnum(2, eventType_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      output.writeMessage(3, getPosition());
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      output.writeMessage(4, getDirection());
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      output.writeInt32(5, playerId_);
    }
    if (((bitField0_ & 0x00000020) != 0)) {
      output.writeInt32(6, affectedPlayerId_);
    }
    if (((bitField0_ & 0x00000040) != 0)) {
      output.writeInt32(7, sequence_);
    }
    if (((bitField0_ & 0x00000080) != 0)) {
      output.writeInt32(8, pingMls_);
    }
    if (((bitField0_ & 0x00000100) != 0)) {
      output.writeInt32(9, teleportId_);
    }
    if (((bitField0_ & 0x00000200) != 0)) {
      output.writeEnum(10, weaponType_);
    }
    if (((bitField0_ & 0x00000400) != 0)) {
      output.writeMessage(11, getProjectile());
    }
    if (((bitField0_ & 0x00000800) != 0)) {
      output.writeEnum(12, powerUp_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, gameId_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(2, eventType_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getPosition());
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getDirection());
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(5, playerId_);
    }
    if (((bitField0_ & 0x00000020) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(6, affectedPlayerId_);
    }
    if (((bitField0_ & 0x00000040) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(7, sequence_);
    }
    if (((bitField0_ & 0x00000080) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(8, pingMls_);
    }
    if (((bitField0_ & 0x00000100) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(9, teleportId_);
    }
    if (((bitField0_ & 0x00000200) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(10, weaponType_);
    }
    if (((bitField0_ & 0x00000400) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(11, getProjectile());
    }
    if (((bitField0_ & 0x00000800) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(12, powerUp_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.beverly.hills.money.gang.proto.PushGameEventCommand)) {
      return super.equals(obj);
    }
    com.beverly.hills.money.gang.proto.PushGameEventCommand other = (com.beverly.hills.money.gang.proto.PushGameEventCommand) obj;

    if (hasGameId() != other.hasGameId()) return false;
    if (hasGameId()) {
      if (getGameId()
          != other.getGameId()) return false;
    }
    if (hasEventType() != other.hasEventType()) return false;
    if (hasEventType()) {
      if (eventType_ != other.eventType_) return false;
    }
    if (hasPosition() != other.hasPosition()) return false;
    if (hasPosition()) {
      if (!getPosition()
          .equals(other.getPosition())) return false;
    }
    if (hasDirection() != other.hasDirection()) return false;
    if (hasDirection()) {
      if (!getDirection()
          .equals(other.getDirection())) return false;
    }
    if (hasPlayerId() != other.hasPlayerId()) return false;
    if (hasPlayerId()) {
      if (getPlayerId()
          != other.getPlayerId()) return false;
    }
    if (hasAffectedPlayerId() != other.hasAffectedPlayerId()) return false;
    if (hasAffectedPlayerId()) {
      if (getAffectedPlayerId()
          != other.getAffectedPlayerId()) return false;
    }
    if (hasSequence() != other.hasSequence()) return false;
    if (hasSequence()) {
      if (getSequence()
          != other.getSequence()) return false;
    }
    if (hasPingMls() != other.hasPingMls()) return false;
    if (hasPingMls()) {
      if (getPingMls()
          != other.getPingMls()) return false;
    }
    if (hasTeleportId() != other.hasTeleportId()) return false;
    if (hasTeleportId()) {
      if (getTeleportId()
          != other.getTeleportId()) return false;
    }
    if (hasWeaponType() != other.hasWeaponType()) return false;
    if (hasWeaponType()) {
      if (weaponType_ != other.weaponType_) return false;
    }
    if (hasProjectile() != other.hasProjectile()) return false;
    if (hasProjectile()) {
      if (!getProjectile()
          .equals(other.getProjectile())) return false;
    }
    if (hasPowerUp() != other.hasPowerUp()) return false;
    if (hasPowerUp()) {
      if (powerUp_ != other.powerUp_) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasGameId()) {
      hash = (37 * hash) + GAMEID_FIELD_NUMBER;
      hash = (53 * hash) + getGameId();
    }
    if (hasEventType()) {
      hash = (37 * hash) + EVENTTYPE_FIELD_NUMBER;
      hash = (53 * hash) + eventType_;
    }
    if (hasPosition()) {
      hash = (37 * hash) + POSITION_FIELD_NUMBER;
      hash = (53 * hash) + getPosition().hashCode();
    }
    if (hasDirection()) {
      hash = (37 * hash) + DIRECTION_FIELD_NUMBER;
      hash = (53 * hash) + getDirection().hashCode();
    }
    if (hasPlayerId()) {
      hash = (37 * hash) + PLAYERID_FIELD_NUMBER;
      hash = (53 * hash) + getPlayerId();
    }
    if (hasAffectedPlayerId()) {
      hash = (37 * hash) + AFFECTEDPLAYERID_FIELD_NUMBER;
      hash = (53 * hash) + getAffectedPlayerId();
    }
    if (hasSequence()) {
      hash = (37 * hash) + SEQUENCE_FIELD_NUMBER;
      hash = (53 * hash) + getSequence();
    }
    if (hasPingMls()) {
      hash = (37 * hash) + PINGMLS_FIELD_NUMBER;
      hash = (53 * hash) + getPingMls();
    }
    if (hasTeleportId()) {
      hash = (37 * hash) + TELEPORTID_FIELD_NUMBER;
      hash = (53 * hash) + getTeleportId();
    }
    if (hasWeaponType()) {
      hash = (37 * hash) + WEAPONTYPE_FIELD_NUMBER;
      hash = (53 * hash) + weaponType_;
    }
    if (hasProjectile()) {
      hash = (37 * hash) + PROJECTILE_FIELD_NUMBER;
      hash = (53 * hash) + getProjectile().hashCode();
    }
    if (hasPowerUp()) {
      hash = (37 * hash) + POWERUP_FIELD_NUMBER;
      hash = (53 * hash) + powerUp_;
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.beverly.hills.money.gang.proto.PushGameEventCommand parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.beverly.hills.money.gang.proto.PushGameEventCommand parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.beverly.hills.money.gang.proto.PushGameEventCommand parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.beverly.hills.money.gang.proto.PushGameEventCommand parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.beverly.hills.money.gang.proto.PushGameEventCommand parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.beverly.hills.money.gang.proto.PushGameEventCommand parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.beverly.hills.money.gang.proto.PushGameEventCommand parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.beverly.hills.money.gang.proto.PushGameEventCommand parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.beverly.hills.money.gang.proto.PushGameEventCommand parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.beverly.hills.money.gang.proto.PushGameEventCommand parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.beverly.hills.money.gang.proto.PushGameEventCommand parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.beverly.hills.money.gang.proto.PushGameEventCommand parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.beverly.hills.money.gang.proto.PushGameEventCommand prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code daikombat.dto.PushGameEventCommand}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:daikombat.dto.PushGameEventCommand)
      com.beverly.hills.money.gang.proto.PushGameEventCommandOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.beverly.hills.money.gang.proto.ServerCommandOuterClass.internal_static_daikombat_dto_PushGameEventCommand_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.beverly.hills.money.gang.proto.ServerCommandOuterClass.internal_static_daikombat_dto_PushGameEventCommand_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.beverly.hills.money.gang.proto.PushGameEventCommand.class, com.beverly.hills.money.gang.proto.PushGameEventCommand.Builder.class);
    }

    // Construct using com.beverly.hills.money.gang.proto.PushGameEventCommand.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getPositionFieldBuilder();
        getDirectionFieldBuilder();
        getProjectileFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      gameId_ = 0;
      eventType_ = 0;
      position_ = null;
      if (positionBuilder_ != null) {
        positionBuilder_.dispose();
        positionBuilder_ = null;
      }
      direction_ = null;
      if (directionBuilder_ != null) {
        directionBuilder_.dispose();
        directionBuilder_ = null;
      }
      playerId_ = 0;
      affectedPlayerId_ = 0;
      sequence_ = 0;
      pingMls_ = 0;
      teleportId_ = 0;
      weaponType_ = 0;
      projectile_ = null;
      if (projectileBuilder_ != null) {
        projectileBuilder_.dispose();
        projectileBuilder_ = null;
      }
      powerUp_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.beverly.hills.money.gang.proto.ServerCommandOuterClass.internal_static_daikombat_dto_PushGameEventCommand_descriptor;
    }

    @java.lang.Override
    public com.beverly.hills.money.gang.proto.PushGameEventCommand getDefaultInstanceForType() {
      return com.beverly.hills.money.gang.proto.PushGameEventCommand.getDefaultInstance();
    }

    @java.lang.Override
    public com.beverly.hills.money.gang.proto.PushGameEventCommand build() {
      com.beverly.hills.money.gang.proto.PushGameEventCommand result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.beverly.hills.money.gang.proto.PushGameEventCommand buildPartial() {
      com.beverly.hills.money.gang.proto.PushGameEventCommand result = new com.beverly.hills.money.gang.proto.PushGameEventCommand(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.beverly.hills.money.gang.proto.PushGameEventCommand result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.gameId_ = gameId_;
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.eventType_ = eventType_;
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.position_ = positionBuilder_ == null
            ? position_
            : positionBuilder_.build();
        to_bitField0_ |= 0x00000004;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.direction_ = directionBuilder_ == null
            ? direction_
            : directionBuilder_.build();
        to_bitField0_ |= 0x00000008;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.playerId_ = playerId_;
        to_bitField0_ |= 0x00000010;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.affectedPlayerId_ = affectedPlayerId_;
        to_bitField0_ |= 0x00000020;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.sequence_ = sequence_;
        to_bitField0_ |= 0x00000040;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.pingMls_ = pingMls_;
        to_bitField0_ |= 0x00000080;
      }
      if (((from_bitField0_ & 0x00000100) != 0)) {
        result.teleportId_ = teleportId_;
        to_bitField0_ |= 0x00000100;
      }
      if (((from_bitField0_ & 0x00000200) != 0)) {
        result.weaponType_ = weaponType_;
        to_bitField0_ |= 0x00000200;
      }
      if (((from_bitField0_ & 0x00000400) != 0)) {
        result.projectile_ = projectileBuilder_ == null
            ? projectile_
            : projectileBuilder_.build();
        to_bitField0_ |= 0x00000400;
      }
      if (((from_bitField0_ & 0x00000800) != 0)) {
        result.powerUp_ = powerUp_;
        to_bitField0_ |= 0x00000800;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.beverly.hills.money.gang.proto.PushGameEventCommand) {
        return mergeFrom((com.beverly.hills.money.gang.proto.PushGameEventCommand)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.beverly.hills.money.gang.proto.PushGameEventCommand other) {
      if (other == com.beverly.hills.money.gang.proto.PushGameEventCommand.getDefaultInstance()) return this;
      if (other.hasGameId()) {
        setGameId(other.getGameId());
      }
      if (other.hasEventType()) {
        setEventType(other.getEventType());
      }
      if (other.hasPosition()) {
        mergePosition(other.getPosition());
      }
      if (other.hasDirection()) {
        mergeDirection(other.getDirection());
      }
      if (other.hasPlayerId()) {
        setPlayerId(other.getPlayerId());
      }
      if (other.hasAffectedPlayerId()) {
        setAffectedPlayerId(other.getAffectedPlayerId());
      }
      if (other.hasSequence()) {
        setSequence(other.getSequence());
      }
      if (other.hasPingMls()) {
        setPingMls(other.getPingMls());
      }
      if (other.hasTeleportId()) {
        setTeleportId(other.getTeleportId());
      }
      if (other.hasWeaponType()) {
        setWeaponType(other.getWeaponType());
      }
      if (other.hasProjectile()) {
        mergeProjectile(other.getProjectile());
      }
      if (other.hasPowerUp()) {
        setPowerUp(other.getPowerUp());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              gameId_ = input.readInt32();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              eventType_ = input.readEnum();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 26: {
              input.readMessage(
                  getPositionFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              input.readMessage(
                  getDirectionFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 40: {
              playerId_ = input.readInt32();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            case 48: {
              affectedPlayerId_ = input.readInt32();
              bitField0_ |= 0x00000020;
              break;
            } // case 48
            case 56: {
              sequence_ = input.readInt32();
              bitField0_ |= 0x00000040;
              break;
            } // case 56
            case 64: {
              pingMls_ = input.readInt32();
              bitField0_ |= 0x00000080;
              break;
            } // case 64
            case 72: {
              teleportId_ = input.readInt32();
              bitField0_ |= 0x00000100;
              break;
            } // case 72
            case 80: {
              weaponType_ = input.readEnum();
              bitField0_ |= 0x00000200;
              break;
            } // case 80
            case 90: {
              input.readMessage(
                  getProjectileFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000400;
              break;
            } // case 90
            case 96: {
              powerUp_ = input.readEnum();
              bitField0_ |= 0x00000800;
              break;
            } // case 96
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int gameId_ ;
    /**
     * <code>optional int32 gameId = 1;</code>
     * @return Whether the gameId field is set.
     */
    @java.lang.Override
    public boolean hasGameId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional int32 gameId = 1;</code>
     * @return The gameId.
     */
    @java.lang.Override
    public int getGameId() {
      return gameId_;
    }
    /**
     * <code>optional int32 gameId = 1;</code>
     * @param value The gameId to set.
     * @return This builder for chaining.
     */
    public Builder setGameId(int value) {

      gameId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 gameId = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearGameId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      gameId_ = 0;
      onChanged();
      return this;
    }

    private int eventType_ = 0;
    /**
     * <code>optional .daikombat.dto.PushGameEventCommand.GameEventType eventType = 2;</code>
     * @return Whether the eventType field is set.
     */
    @java.lang.Override public boolean hasEventType() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional .daikombat.dto.PushGameEventCommand.GameEventType eventType = 2;</code>
     * @return The enum numeric value on the wire for eventType.
     */
    @java.lang.Override public int getEventTypeValue() {
      return eventType_;
    }
    /**
     * <code>optional .daikombat.dto.PushGameEventCommand.GameEventType eventType = 2;</code>
     * @param value The enum numeric value on the wire for eventType to set.
     * @return This builder for chaining.
     */
    public Builder setEventTypeValue(int value) {
      eventType_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>optional .daikombat.dto.PushGameEventCommand.GameEventType eventType = 2;</code>
     * @return The eventType.
     */
    @java.lang.Override
    public com.beverly.hills.money.gang.proto.PushGameEventCommand.GameEventType getEventType() {
      com.beverly.hills.money.gang.proto.PushGameEventCommand.GameEventType result = com.beverly.hills.money.gang.proto.PushGameEventCommand.GameEventType.forNumber(eventType_);
      return result == null ? com.beverly.hills.money.gang.proto.PushGameEventCommand.GameEventType.UNRECOGNIZED : result;
    }
    /**
     * <code>optional .daikombat.dto.PushGameEventCommand.GameEventType eventType = 2;</code>
     * @param value The eventType to set.
     * @return This builder for chaining.
     */
    public Builder setEventType(com.beverly.hills.money.gang.proto.PushGameEventCommand.GameEventType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000002;
      eventType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>optional .daikombat.dto.PushGameEventCommand.GameEventType eventType = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearEventType() {
      bitField0_ = (bitField0_ & ~0x00000002);
      eventType_ = 0;
      onChanged();
      return this;
    }

    private com.beverly.hills.money.gang.proto.Vector position_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.beverly.hills.money.gang.proto.Vector, com.beverly.hills.money.gang.proto.Vector.Builder, com.beverly.hills.money.gang.proto.VectorOrBuilder> positionBuilder_;
    /**
     * <code>optional .daikombat.dto.Vector position = 3;</code>
     * @return Whether the position field is set.
     */
    public boolean hasPosition() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional .daikombat.dto.Vector position = 3;</code>
     * @return The position.
     */
    public com.beverly.hills.money.gang.proto.Vector getPosition() {
      if (positionBuilder_ == null) {
        return position_ == null ? com.beverly.hills.money.gang.proto.Vector.getDefaultInstance() : position_;
      } else {
        return positionBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .daikombat.dto.Vector position = 3;</code>
     */
    public Builder setPosition(com.beverly.hills.money.gang.proto.Vector value) {
      if (positionBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        position_ = value;
      } else {
        positionBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>optional .daikombat.dto.Vector position = 3;</code>
     */
    public Builder setPosition(
        com.beverly.hills.money.gang.proto.Vector.Builder builderForValue) {
      if (positionBuilder_ == null) {
        position_ = builderForValue.build();
      } else {
        positionBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>optional .daikombat.dto.Vector position = 3;</code>
     */
    public Builder mergePosition(com.beverly.hills.money.gang.proto.Vector value) {
      if (positionBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0) &&
          position_ != null &&
          position_ != com.beverly.hills.money.gang.proto.Vector.getDefaultInstance()) {
          getPositionBuilder().mergeFrom(value);
        } else {
          position_ = value;
        }
      } else {
        positionBuilder_.mergeFrom(value);
      }
      if (position_ != null) {
        bitField0_ |= 0x00000004;
        onChanged();
      }
      return this;
    }
    /**
     * <code>optional .daikombat.dto.Vector position = 3;</code>
     */
    public Builder clearPosition() {
      bitField0_ = (bitField0_ & ~0x00000004);
      position_ = null;
      if (positionBuilder_ != null) {
        positionBuilder_.dispose();
        positionBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>optional .daikombat.dto.Vector position = 3;</code>
     */
    public com.beverly.hills.money.gang.proto.Vector.Builder getPositionBuilder() {
      bitField0_ |= 0x00000004;
      onChanged();
      return getPositionFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .daikombat.dto.Vector position = 3;</code>
     */
    public com.beverly.hills.money.gang.proto.VectorOrBuilder getPositionOrBuilder() {
      if (positionBuilder_ != null) {
        return positionBuilder_.getMessageOrBuilder();
      } else {
        return position_ == null ?
            com.beverly.hills.money.gang.proto.Vector.getDefaultInstance() : position_;
      }
    }
    /**
     * <code>optional .daikombat.dto.Vector position = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.beverly.hills.money.gang.proto.Vector, com.beverly.hills.money.gang.proto.Vector.Builder, com.beverly.hills.money.gang.proto.VectorOrBuilder> 
        getPositionFieldBuilder() {
      if (positionBuilder_ == null) {
        positionBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.beverly.hills.money.gang.proto.Vector, com.beverly.hills.money.gang.proto.Vector.Builder, com.beverly.hills.money.gang.proto.VectorOrBuilder>(
                getPosition(),
                getParentForChildren(),
                isClean());
        position_ = null;
      }
      return positionBuilder_;
    }

    private com.beverly.hills.money.gang.proto.Vector direction_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.beverly.hills.money.gang.proto.Vector, com.beverly.hills.money.gang.proto.Vector.Builder, com.beverly.hills.money.gang.proto.VectorOrBuilder> directionBuilder_;
    /**
     * <code>optional .daikombat.dto.Vector direction = 4;</code>
     * @return Whether the direction field is set.
     */
    public boolean hasDirection() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional .daikombat.dto.Vector direction = 4;</code>
     * @return The direction.
     */
    public com.beverly.hills.money.gang.proto.Vector getDirection() {
      if (directionBuilder_ == null) {
        return direction_ == null ? com.beverly.hills.money.gang.proto.Vector.getDefaultInstance() : direction_;
      } else {
        return directionBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .daikombat.dto.Vector direction = 4;</code>
     */
    public Builder setDirection(com.beverly.hills.money.gang.proto.Vector value) {
      if (directionBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        direction_ = value;
      } else {
        directionBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>optional .daikombat.dto.Vector direction = 4;</code>
     */
    public Builder setDirection(
        com.beverly.hills.money.gang.proto.Vector.Builder builderForValue) {
      if (directionBuilder_ == null) {
        direction_ = builderForValue.build();
      } else {
        directionBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>optional .daikombat.dto.Vector direction = 4;</code>
     */
    public Builder mergeDirection(com.beverly.hills.money.gang.proto.Vector value) {
      if (directionBuilder_ == null) {
        if (((bitField0_ & 0x00000008) != 0) &&
          direction_ != null &&
          direction_ != com.beverly.hills.money.gang.proto.Vector.getDefaultInstance()) {
          getDirectionBuilder().mergeFrom(value);
        } else {
          direction_ = value;
        }
      } else {
        directionBuilder_.mergeFrom(value);
      }
      if (direction_ != null) {
        bitField0_ |= 0x00000008;
        onChanged();
      }
      return this;
    }
    /**
     * <code>optional .daikombat.dto.Vector direction = 4;</code>
     */
    public Builder clearDirection() {
      bitField0_ = (bitField0_ & ~0x00000008);
      direction_ = null;
      if (directionBuilder_ != null) {
        directionBuilder_.dispose();
        directionBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>optional .daikombat.dto.Vector direction = 4;</code>
     */
    public com.beverly.hills.money.gang.proto.Vector.Builder getDirectionBuilder() {
      bitField0_ |= 0x00000008;
      onChanged();
      return getDirectionFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .daikombat.dto.Vector direction = 4;</code>
     */
    public com.beverly.hills.money.gang.proto.VectorOrBuilder getDirectionOrBuilder() {
      if (directionBuilder_ != null) {
        return directionBuilder_.getMessageOrBuilder();
      } else {
        return direction_ == null ?
            com.beverly.hills.money.gang.proto.Vector.getDefaultInstance() : direction_;
      }
    }
    /**
     * <code>optional .daikombat.dto.Vector direction = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.beverly.hills.money.gang.proto.Vector, com.beverly.hills.money.gang.proto.Vector.Builder, com.beverly.hills.money.gang.proto.VectorOrBuilder> 
        getDirectionFieldBuilder() {
      if (directionBuilder_ == null) {
        directionBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.beverly.hills.money.gang.proto.Vector, com.beverly.hills.money.gang.proto.Vector.Builder, com.beverly.hills.money.gang.proto.VectorOrBuilder>(
                getDirection(),
                getParentForChildren(),
                isClean());
        direction_ = null;
      }
      return directionBuilder_;
    }

    private int playerId_ ;
    /**
     * <code>optional int32 playerId = 5;</code>
     * @return Whether the playerId field is set.
     */
    @java.lang.Override
    public boolean hasPlayerId() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>optional int32 playerId = 5;</code>
     * @return The playerId.
     */
    @java.lang.Override
    public int getPlayerId() {
      return playerId_;
    }
    /**
     * <code>optional int32 playerId = 5;</code>
     * @param value The playerId to set.
     * @return This builder for chaining.
     */
    public Builder setPlayerId(int value) {

      playerId_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 playerId = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearPlayerId() {
      bitField0_ = (bitField0_ & ~0x00000010);
      playerId_ = 0;
      onChanged();
      return this;
    }

    private int affectedPlayerId_ ;
    /**
     * <code>optional int32 affectedPlayerId = 6;</code>
     * @return Whether the affectedPlayerId field is set.
     */
    @java.lang.Override
    public boolean hasAffectedPlayerId() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>optional int32 affectedPlayerId = 6;</code>
     * @return The affectedPlayerId.
     */
    @java.lang.Override
    public int getAffectedPlayerId() {
      return affectedPlayerId_;
    }
    /**
     * <code>optional int32 affectedPlayerId = 6;</code>
     * @param value The affectedPlayerId to set.
     * @return This builder for chaining.
     */
    public Builder setAffectedPlayerId(int value) {

      affectedPlayerId_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 affectedPlayerId = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearAffectedPlayerId() {
      bitField0_ = (bitField0_ & ~0x00000020);
      affectedPlayerId_ = 0;
      onChanged();
      return this;
    }

    private int sequence_ ;
    /**
     * <code>optional int32 sequence = 7;</code>
     * @return Whether the sequence field is set.
     */
    @java.lang.Override
    public boolean hasSequence() {
      return ((bitField0_ & 0x00000040) != 0);
    }
    /**
     * <code>optional int32 sequence = 7;</code>
     * @return The sequence.
     */
    @java.lang.Override
    public int getSequence() {
      return sequence_;
    }
    /**
     * <code>optional int32 sequence = 7;</code>
     * @param value The sequence to set.
     * @return This builder for chaining.
     */
    public Builder setSequence(int value) {

      sequence_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 sequence = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearSequence() {
      bitField0_ = (bitField0_ & ~0x00000040);
      sequence_ = 0;
      onChanged();
      return this;
    }

    private int pingMls_ ;
    /**
     * <code>optional int32 pingMls = 8;</code>
     * @return Whether the pingMls field is set.
     */
    @java.lang.Override
    public boolean hasPingMls() {
      return ((bitField0_ & 0x00000080) != 0);
    }
    /**
     * <code>optional int32 pingMls = 8;</code>
     * @return The pingMls.
     */
    @java.lang.Override
    public int getPingMls() {
      return pingMls_;
    }
    /**
     * <code>optional int32 pingMls = 8;</code>
     * @param value The pingMls to set.
     * @return This builder for chaining.
     */
    public Builder setPingMls(int value) {

      pingMls_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 pingMls = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearPingMls() {
      bitField0_ = (bitField0_ & ~0x00000080);
      pingMls_ = 0;
      onChanged();
      return this;
    }

    private int teleportId_ ;
    /**
     * <code>optional int32 teleportId = 9;</code>
     * @return Whether the teleportId field is set.
     */
    @java.lang.Override
    public boolean hasTeleportId() {
      return ((bitField0_ & 0x00000100) != 0);
    }
    /**
     * <code>optional int32 teleportId = 9;</code>
     * @return The teleportId.
     */
    @java.lang.Override
    public int getTeleportId() {
      return teleportId_;
    }
    /**
     * <code>optional int32 teleportId = 9;</code>
     * @param value The teleportId to set.
     * @return This builder for chaining.
     */
    public Builder setTeleportId(int value) {

      teleportId_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 teleportId = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearTeleportId() {
      bitField0_ = (bitField0_ & ~0x00000100);
      teleportId_ = 0;
      onChanged();
      return this;
    }

    private int weaponType_ = 0;
    /**
     * <code>optional .daikombat.dto.WeaponType weaponType = 10;</code>
     * @return Whether the weaponType field is set.
     */
    @java.lang.Override public boolean hasWeaponType() {
      return ((bitField0_ & 0x00000200) != 0);
    }
    /**
     * <code>optional .daikombat.dto.WeaponType weaponType = 10;</code>
     * @return The enum numeric value on the wire for weaponType.
     */
    @java.lang.Override public int getWeaponTypeValue() {
      return weaponType_;
    }
    /**
     * <code>optional .daikombat.dto.WeaponType weaponType = 10;</code>
     * @param value The enum numeric value on the wire for weaponType to set.
     * @return This builder for chaining.
     */
    public Builder setWeaponTypeValue(int value) {
      weaponType_ = value;
      bitField0_ |= 0x00000200;
      onChanged();
      return this;
    }
    /**
     * <code>optional .daikombat.dto.WeaponType weaponType = 10;</code>
     * @return The weaponType.
     */
    @java.lang.Override
    public com.beverly.hills.money.gang.proto.WeaponType getWeaponType() {
      com.beverly.hills.money.gang.proto.WeaponType result = com.beverly.hills.money.gang.proto.WeaponType.forNumber(weaponType_);
      return result == null ? com.beverly.hills.money.gang.proto.WeaponType.UNRECOGNIZED : result;
    }
    /**
     * <code>optional .daikombat.dto.WeaponType weaponType = 10;</code>
     * @param value The weaponType to set.
     * @return This builder for chaining.
     */
    public Builder setWeaponType(com.beverly.hills.money.gang.proto.WeaponType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000200;
      weaponType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>optional .daikombat.dto.WeaponType weaponType = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearWeaponType() {
      bitField0_ = (bitField0_ & ~0x00000200);
      weaponType_ = 0;
      onChanged();
      return this;
    }

    private com.beverly.hills.money.gang.proto.ProjectileCoordinates projectile_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.beverly.hills.money.gang.proto.ProjectileCoordinates, com.beverly.hills.money.gang.proto.ProjectileCoordinates.Builder, com.beverly.hills.money.gang.proto.ProjectileCoordinatesOrBuilder> projectileBuilder_;
    /**
     * <code>optional .daikombat.dto.ProjectileCoordinates projectile = 11;</code>
     * @return Whether the projectile field is set.
     */
    public boolean hasProjectile() {
      return ((bitField0_ & 0x00000400) != 0);
    }
    /**
     * <code>optional .daikombat.dto.ProjectileCoordinates projectile = 11;</code>
     * @return The projectile.
     */
    public com.beverly.hills.money.gang.proto.ProjectileCoordinates getProjectile() {
      if (projectileBuilder_ == null) {
        return projectile_ == null ? com.beverly.hills.money.gang.proto.ProjectileCoordinates.getDefaultInstance() : projectile_;
      } else {
        return projectileBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .daikombat.dto.ProjectileCoordinates projectile = 11;</code>
     */
    public Builder setProjectile(com.beverly.hills.money.gang.proto.ProjectileCoordinates value) {
      if (projectileBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        projectile_ = value;
      } else {
        projectileBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000400;
      onChanged();
      return this;
    }
    /**
     * <code>optional .daikombat.dto.ProjectileCoordinates projectile = 11;</code>
     */
    public Builder setProjectile(
        com.beverly.hills.money.gang.proto.ProjectileCoordinates.Builder builderForValue) {
      if (projectileBuilder_ == null) {
        projectile_ = builderForValue.build();
      } else {
        projectileBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000400;
      onChanged();
      return this;
    }
    /**
     * <code>optional .daikombat.dto.ProjectileCoordinates projectile = 11;</code>
     */
    public Builder mergeProjectile(com.beverly.hills.money.gang.proto.ProjectileCoordinates value) {
      if (projectileBuilder_ == null) {
        if (((bitField0_ & 0x00000400) != 0) &&
          projectile_ != null &&
          projectile_ != com.beverly.hills.money.gang.proto.ProjectileCoordinates.getDefaultInstance()) {
          getProjectileBuilder().mergeFrom(value);
        } else {
          projectile_ = value;
        }
      } else {
        projectileBuilder_.mergeFrom(value);
      }
      if (projectile_ != null) {
        bitField0_ |= 0x00000400;
        onChanged();
      }
      return this;
    }
    /**
     * <code>optional .daikombat.dto.ProjectileCoordinates projectile = 11;</code>
     */
    public Builder clearProjectile() {
      bitField0_ = (bitField0_ & ~0x00000400);
      projectile_ = null;
      if (projectileBuilder_ != null) {
        projectileBuilder_.dispose();
        projectileBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>optional .daikombat.dto.ProjectileCoordinates projectile = 11;</code>
     */
    public com.beverly.hills.money.gang.proto.ProjectileCoordinates.Builder getProjectileBuilder() {
      bitField0_ |= 0x00000400;
      onChanged();
      return getProjectileFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .daikombat.dto.ProjectileCoordinates projectile = 11;</code>
     */
    public com.beverly.hills.money.gang.proto.ProjectileCoordinatesOrBuilder getProjectileOrBuilder() {
      if (projectileBuilder_ != null) {
        return projectileBuilder_.getMessageOrBuilder();
      } else {
        return projectile_ == null ?
            com.beverly.hills.money.gang.proto.ProjectileCoordinates.getDefaultInstance() : projectile_;
      }
    }
    /**
     * <code>optional .daikombat.dto.ProjectileCoordinates projectile = 11;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.beverly.hills.money.gang.proto.ProjectileCoordinates, com.beverly.hills.money.gang.proto.ProjectileCoordinates.Builder, com.beverly.hills.money.gang.proto.ProjectileCoordinatesOrBuilder> 
        getProjectileFieldBuilder() {
      if (projectileBuilder_ == null) {
        projectileBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.beverly.hills.money.gang.proto.ProjectileCoordinates, com.beverly.hills.money.gang.proto.ProjectileCoordinates.Builder, com.beverly.hills.money.gang.proto.ProjectileCoordinatesOrBuilder>(
                getProjectile(),
                getParentForChildren(),
                isClean());
        projectile_ = null;
      }
      return projectileBuilder_;
    }

    private int powerUp_ = 0;
    /**
     * <code>optional .daikombat.dto.GamePowerUpType powerUp = 12;</code>
     * @return Whether the powerUp field is set.
     */
    @java.lang.Override public boolean hasPowerUp() {
      return ((bitField0_ & 0x00000800) != 0);
    }
    /**
     * <code>optional .daikombat.dto.GamePowerUpType powerUp = 12;</code>
     * @return The enum numeric value on the wire for powerUp.
     */
    @java.lang.Override public int getPowerUpValue() {
      return powerUp_;
    }
    /**
     * <code>optional .daikombat.dto.GamePowerUpType powerUp = 12;</code>
     * @param value The enum numeric value on the wire for powerUp to set.
     * @return This builder for chaining.
     */
    public Builder setPowerUpValue(int value) {
      powerUp_ = value;
      bitField0_ |= 0x00000800;
      onChanged();
      return this;
    }
    /**
     * <code>optional .daikombat.dto.GamePowerUpType powerUp = 12;</code>
     * @return The powerUp.
     */
    @java.lang.Override
    public com.beverly.hills.money.gang.proto.GamePowerUpType getPowerUp() {
      com.beverly.hills.money.gang.proto.GamePowerUpType result = com.beverly.hills.money.gang.proto.GamePowerUpType.forNumber(powerUp_);
      return result == null ? com.beverly.hills.money.gang.proto.GamePowerUpType.UNRECOGNIZED : result;
    }
    /**
     * <code>optional .daikombat.dto.GamePowerUpType powerUp = 12;</code>
     * @param value The powerUp to set.
     * @return This builder for chaining.
     */
    public Builder setPowerUp(com.beverly.hills.money.gang.proto.GamePowerUpType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000800;
      powerUp_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>optional .daikombat.dto.GamePowerUpType powerUp = 12;</code>
     * @return This builder for chaining.
     */
    public Builder clearPowerUp() {
      bitField0_ = (bitField0_ & ~0x00000800);
      powerUp_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:daikombat.dto.PushGameEventCommand)
  }

  // @@protoc_insertion_point(class_scope:daikombat.dto.PushGameEventCommand)
  private static final com.beverly.hills.money.gang.proto.PushGameEventCommand DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.beverly.hills.money.gang.proto.PushGameEventCommand();
  }

  public static com.beverly.hills.money.gang.proto.PushGameEventCommand getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PushGameEventCommand>
      PARSER = new com.google.protobuf.AbstractParser<PushGameEventCommand>() {
    @java.lang.Override
    public PushGameEventCommand parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<PushGameEventCommand> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PushGameEventCommand> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.beverly.hills.money.gang.proto.PushGameEventCommand getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

