// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: schema/src/main/resources/server-command.proto

// Protobuf Java Version: 3.25.0
package com.beverly.hills.money.gang.proto;

public final class ServerCommandOuterClass {
  private ServerCommandOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_daikombat_dto_ServerCommand_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_daikombat_dto_ServerCommand_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_daikombat_dto_GetServerInfoCommand_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_daikombat_dto_GetServerInfoCommand_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_daikombat_dto_PingCommand_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_daikombat_dto_PingCommand_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_daikombat_dto_PushChatEventCommand_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_daikombat_dto_PushChatEventCommand_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_daikombat_dto_JoinGameCommand_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_daikombat_dto_JoinGameCommand_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_daikombat_dto_MergeConnectionCommand_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_daikombat_dto_MergeConnectionCommand_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_daikombat_dto_RespawnCommand_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_daikombat_dto_RespawnCommand_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_daikombat_dto_PushGameEventCommand_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_daikombat_dto_PushGameEventCommand_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n.schema/src/main/resources/server-comma" +
      "nd.proto\022\rdaikombat.dto\032-schema/src/main" +
      "/resources/server-common.proto\"\343\003\n\rServe" +
      "rCommand\022\021\n\004hmac\030\002 \001(\014H\001\210\001\001\022:\n\013chatComma" +
      "nd\030\003 \001(\0132#.daikombat.dto.PushChatEventCo" +
      "mmandH\000\022:\n\013gameCommand\030\004 \001(\0132#.daikombat" +
      ".dto.PushGameEventCommandH\000\0229\n\017joinGameC" +
      "ommand\030\005 \001(\0132\036.daikombat.dto.JoinGameCom" +
      "mandH\000\022C\n\024getServerInfoCommand\030\006 \001(\0132#.d" +
      "aikombat.dto.GetServerInfoCommandH\000\0221\n\013p" +
      "ingCommand\030\007 \001(\0132\032.daikombat.dto.PingCom" +
      "mandH\000\0227\n\016respawnCommand\030\010 \001(\0132\035.daikomb" +
      "at.dto.RespawnCommandH\000\022G\n\026mergeConnecti" +
      "onCommand\030\t \001(\0132%.daikombat.dto.MergeCon" +
      "nectionCommandH\000B\t\n\007commandB\007\n\005_hmac\"\\\n\024" +
      "GetServerInfoCommand\0224\n\013playerClass\030\001 \001(" +
      "\0162\032.daikombat.dto.PlayerClassH\000\210\001\001B\016\n\014_p" +
      "layerClass\"\r\n\013PingCommand\"|\n\024PushChatEve" +
      "ntCommand\022\023\n\006gameId\030\001 \001(\005H\000\210\001\001\022\024\n\007messag" +
      "e\030\002 \001(\tH\001\210\001\001\022\025\n\010playerId\030\003 \001(\005H\002\210\001\001B\t\n\007_" +
      "gameIdB\n\n\010_messageB\013\n\t_playerId\"\261\002\n\017Join" +
      "GameCommand\022\023\n\006gameId\030\001 \001(\005H\000\210\001\001\022\024\n\007vers" +
      "ion\030\002 \001(\tH\001\210\001\001\022\027\n\nplayerName\030\003 \001(\tH\002\210\001\001\022" +
      "1\n\004skin\030\004 \001(\0162\036.daikombat.dto.PlayerSkin" +
      "ColorH\003\210\001\001\022\035\n\020recoveryPlayerId\030\005 \001(\005H\004\210\001" +
      "\001\0224\n\013playerClass\030\006 \001(\0162\032.daikombat.dto.P" +
      "layerClassH\005\210\001\001B\t\n\007_gameIdB\n\n\010_versionB\r" +
      "\n\013_playerNameB\007\n\005_skinB\023\n\021_recoveryPlaye" +
      "rIdB\016\n\014_playerClass\"\\\n\026MergeConnectionCo" +
      "mmand\022\023\n\006gameId\030\001 \001(\005H\000\210\001\001\022\025\n\010playerId\030\002" +
      " \001(\005H\001\210\001\001B\t\n\007_gameIdB\013\n\t_playerId\"T\n\016Res" +
      "pawnCommand\022\023\n\006gameId\030\001 \001(\005H\000\210\001\001\022\025\n\010play" +
      "erId\030\002 \001(\005H\001\210\001\001B\t\n\007_gameIdB\013\n\t_playerId\"" +
      "\356\005\n\024PushGameEventCommand\022\023\n\006gameId\030\001 \001(\005" +
      "H\000\210\001\001\022I\n\teventType\030\002 \001(\01621.daikombat.dto" +
      ".PushGameEventCommand.GameEventTypeH\001\210\001\001" +
      "\022,\n\010position\030\003 \001(\0132\025.daikombat.dto.Vecto" +
      "rH\002\210\001\001\022-\n\tdirection\030\004 \001(\0132\025.daikombat.dt" +
      "o.VectorH\003\210\001\001\022\025\n\010playerId\030\005 \001(\005H\004\210\001\001\022\035\n\020" +
      "affectedPlayerId\030\006 \001(\005H\005\210\001\001\022\025\n\010sequence\030" +
      "\007 \001(\005H\006\210\001\001\022\024\n\007pingMls\030\010 \001(\005H\007\210\001\001\022\027\n\ntele" +
      "portId\030\t \001(\005H\010\210\001\001\0222\n\nweaponType\030\n \001(\0162\031." +
      "daikombat.dto.WeaponTypeH\t\210\001\001\0227\n\nproject" +
      "ile\030\013 \001(\0132\036.daikombat.dto.ProjectileStat" +
      "sH\n\210\001\001\"\223\001\n\rGameEventType\022\010\n\004MOVE\020\000\022\n\n\006AT" +
      "TACK\020\001\022\030\n\024QUAD_DAMAGE_POWER_UP\020\002\022\031\n\025INVI" +
      "SIBILITY_POWER_UP\020\003\022\024\n\020DEFENCE_POWER_UP\020" +
      "\004\022\014\n\010TELEPORT\020\005\022\023\n\017HEALTH_POWER_UP\020\006B\t\n\007" +
      "_gameIdB\014\n\n_eventTypeB\013\n\t_positionB\014\n\n_d" +
      "irectionB\013\n\t_playerIdB\023\n\021_affectedPlayer" +
      "IdB\013\n\t_sequenceB\n\n\010_pingMlsB\r\n\013_teleport" +
      "IdB\r\n\013_weaponTypeB\r\n\013_projectileB&\n\"com." +
      "beverly.hills.money.gang.protoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.beverly.hills.money.gang.proto.ServerCommon.getDescriptor(),
        });
    internal_static_daikombat_dto_ServerCommand_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_daikombat_dto_ServerCommand_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_daikombat_dto_ServerCommand_descriptor,
        new java.lang.String[] { "Hmac", "ChatCommand", "GameCommand", "JoinGameCommand", "GetServerInfoCommand", "PingCommand", "RespawnCommand", "MergeConnectionCommand", "Command", });
    internal_static_daikombat_dto_GetServerInfoCommand_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_daikombat_dto_GetServerInfoCommand_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_daikombat_dto_GetServerInfoCommand_descriptor,
        new java.lang.String[] { "PlayerClass", });
    internal_static_daikombat_dto_PingCommand_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_daikombat_dto_PingCommand_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_daikombat_dto_PingCommand_descriptor,
        new java.lang.String[] { });
    internal_static_daikombat_dto_PushChatEventCommand_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_daikombat_dto_PushChatEventCommand_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_daikombat_dto_PushChatEventCommand_descriptor,
        new java.lang.String[] { "GameId", "Message", "PlayerId", });
    internal_static_daikombat_dto_JoinGameCommand_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_daikombat_dto_JoinGameCommand_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_daikombat_dto_JoinGameCommand_descriptor,
        new java.lang.String[] { "GameId", "Version", "PlayerName", "Skin", "RecoveryPlayerId", "PlayerClass", });
    internal_static_daikombat_dto_MergeConnectionCommand_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_daikombat_dto_MergeConnectionCommand_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_daikombat_dto_MergeConnectionCommand_descriptor,
        new java.lang.String[] { "GameId", "PlayerId", });
    internal_static_daikombat_dto_RespawnCommand_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_daikombat_dto_RespawnCommand_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_daikombat_dto_RespawnCommand_descriptor,
        new java.lang.String[] { "GameId", "PlayerId", });
    internal_static_daikombat_dto_PushGameEventCommand_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_daikombat_dto_PushGameEventCommand_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_daikombat_dto_PushGameEventCommand_descriptor,
        new java.lang.String[] { "GameId", "EventType", "Position", "Direction", "PlayerId", "AffectedPlayerId", "Sequence", "PingMls", "TeleportId", "WeaponType", "Projectile", });
    com.beverly.hills.money.gang.proto.ServerCommon.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
