// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: schema/src/main/resources/server-response.proto

// Protobuf Java Version: 3.25.0
package com.beverly.hills.money.gang.proto;

public interface ServerResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:daikombat.dto.ServerResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.daikombat.dto.ServerResponse.ErrorEvent errorEvent = 1;</code>
   * @return Whether the errorEvent field is set.
   */
  boolean hasErrorEvent();
  /**
   * <code>.daikombat.dto.ServerResponse.ErrorEvent errorEvent = 1;</code>
   * @return The errorEvent.
   */
  com.beverly.hills.money.gang.proto.ServerResponse.ErrorEvent getErrorEvent();
  /**
   * <code>.daikombat.dto.ServerResponse.ErrorEvent errorEvent = 1;</code>
   */
  com.beverly.hills.money.gang.proto.ServerResponse.ErrorEventOrBuilder getErrorEventOrBuilder();

  /**
   * <code>.daikombat.dto.ServerResponse.ChatEvent chatEvents = 2;</code>
   * @return Whether the chatEvents field is set.
   */
  boolean hasChatEvents();
  /**
   * <code>.daikombat.dto.ServerResponse.ChatEvent chatEvents = 2;</code>
   * @return The chatEvents.
   */
  com.beverly.hills.money.gang.proto.ServerResponse.ChatEvent getChatEvents();
  /**
   * <code>.daikombat.dto.ServerResponse.ChatEvent chatEvents = 2;</code>
   */
  com.beverly.hills.money.gang.proto.ServerResponse.ChatEventOrBuilder getChatEventsOrBuilder();

  /**
   * <code>.daikombat.dto.ServerResponse.GameEvents gameEvents = 3;</code>
   * @return Whether the gameEvents field is set.
   */
  boolean hasGameEvents();
  /**
   * <code>.daikombat.dto.ServerResponse.GameEvents gameEvents = 3;</code>
   * @return The gameEvents.
   */
  com.beverly.hills.money.gang.proto.ServerResponse.GameEvents getGameEvents();
  /**
   * <code>.daikombat.dto.ServerResponse.GameEvents gameEvents = 3;</code>
   */
  com.beverly.hills.money.gang.proto.ServerResponse.GameEventsOrBuilder getGameEventsOrBuilder();

  /**
   * <code>.daikombat.dto.ServerResponse.ServerInfo serverInfo = 4;</code>
   * @return Whether the serverInfo field is set.
   */
  boolean hasServerInfo();
  /**
   * <code>.daikombat.dto.ServerResponse.ServerInfo serverInfo = 4;</code>
   * @return The serverInfo.
   */
  com.beverly.hills.money.gang.proto.ServerResponse.ServerInfo getServerInfo();
  /**
   * <code>.daikombat.dto.ServerResponse.ServerInfo serverInfo = 4;</code>
   */
  com.beverly.hills.money.gang.proto.ServerResponse.ServerInfoOrBuilder getServerInfoOrBuilder();

  /**
   * <code>.daikombat.dto.ServerResponse.Ping ping = 5;</code>
   * @return Whether the ping field is set.
   */
  boolean hasPing();
  /**
   * <code>.daikombat.dto.ServerResponse.Ping ping = 5;</code>
   * @return The ping.
   */
  com.beverly.hills.money.gang.proto.ServerResponse.Ping getPing();
  /**
   * <code>.daikombat.dto.ServerResponse.Ping ping = 5;</code>
   */
  com.beverly.hills.money.gang.proto.ServerResponse.PingOrBuilder getPingOrBuilder();

  /**
   * <code>.daikombat.dto.ServerResponse.GameOver gameOver = 6;</code>
   * @return Whether the gameOver field is set.
   */
  boolean hasGameOver();
  /**
   * <code>.daikombat.dto.ServerResponse.GameOver gameOver = 6;</code>
   * @return The gameOver.
   */
  com.beverly.hills.money.gang.proto.ServerResponse.GameOver getGameOver();
  /**
   * <code>.daikombat.dto.ServerResponse.GameOver gameOver = 6;</code>
   */
  com.beverly.hills.money.gang.proto.ServerResponse.GameOverOrBuilder getGameOverOrBuilder();

  /**
   * <code>.daikombat.dto.ServerResponse.PowerUpSpawnEvent powerUpSpawn = 7;</code>
   * @return Whether the powerUpSpawn field is set.
   */
  boolean hasPowerUpSpawn();
  /**
   * <code>.daikombat.dto.ServerResponse.PowerUpSpawnEvent powerUpSpawn = 7;</code>
   * @return The powerUpSpawn.
   */
  com.beverly.hills.money.gang.proto.ServerResponse.PowerUpSpawnEvent getPowerUpSpawn();
  /**
   * <code>.daikombat.dto.ServerResponse.PowerUpSpawnEvent powerUpSpawn = 7;</code>
   */
  com.beverly.hills.money.gang.proto.ServerResponse.PowerUpSpawnEventOrBuilder getPowerUpSpawnOrBuilder();

  /**
   * <code>.daikombat.dto.ServerResponse.TeleportSpawnEvent teleportSpawn = 8;</code>
   * @return Whether the teleportSpawn field is set.
   */
  boolean hasTeleportSpawn();
  /**
   * <code>.daikombat.dto.ServerResponse.TeleportSpawnEvent teleportSpawn = 8;</code>
   * @return The teleportSpawn.
   */
  com.beverly.hills.money.gang.proto.ServerResponse.TeleportSpawnEvent getTeleportSpawn();
  /**
   * <code>.daikombat.dto.ServerResponse.TeleportSpawnEvent teleportSpawn = 8;</code>
   */
  com.beverly.hills.money.gang.proto.ServerResponse.TeleportSpawnEventOrBuilder getTeleportSpawnOrBuilder();

  /**
   * <code>.daikombat.dto.MapAssets mapAssets = 9;</code>
   * @return Whether the mapAssets field is set.
   */
  boolean hasMapAssets();
  /**
   * <code>.daikombat.dto.MapAssets mapAssets = 9;</code>
   * @return The mapAssets.
   */
  com.beverly.hills.money.gang.proto.MapAssets getMapAssets();
  /**
   * <code>.daikombat.dto.MapAssets mapAssets = 9;</code>
   */
  com.beverly.hills.money.gang.proto.MapAssetsOrBuilder getMapAssetsOrBuilder();

  com.beverly.hills.money.gang.proto.ServerResponse.ResponseCase getResponseCase();
}
