// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: schema/src/main/resources/server-command.proto

// Protobuf Java Version: 3.25.0
package com.beverly.hills.money.gang.proto;

public final class ServerCommandOuterClass {
  private ServerCommandOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_daikombat_dto_ServerCommand_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_daikombat_dto_ServerCommand_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_daikombat_dto_GetServerInfoCommand_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_daikombat_dto_GetServerInfoCommand_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_daikombat_dto_DownloadMapAssetsCommand_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_daikombat_dto_DownloadMapAssetsCommand_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_daikombat_dto_PingCommand_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_daikombat_dto_PingCommand_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_daikombat_dto_PushChatEventCommand_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_daikombat_dto_PushChatEventCommand_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_daikombat_dto_JoinGameCommand_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_daikombat_dto_JoinGameCommand_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_daikombat_dto_RespawnCommand_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_daikombat_dto_RespawnCommand_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_daikombat_dto_PushGameEventCommand_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_daikombat_dto_PushGameEventCommand_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n.schema/src/main/resources/server-comma" +
      "nd.proto\022\rdaikombat.dto\032-schema/src/main" +
      "/resources/server-common.proto\"\313\003\n\rServe" +
      "rCommand\022:\n\013chatCommand\030\003 \001(\0132#.daikomba" +
      "t.dto.PushChatEventCommandH\000\022:\n\013gameComm" +
      "and\030\004 \001(\0132#.daikombat.dto.PushGameEventC" +
      "ommandH\000\0229\n\017joinGameCommand\030\005 \001(\0132\036.daik" +
      "ombat.dto.JoinGameCommandH\000\022C\n\024getServer" +
      "InfoCommand\030\006 \001(\0132#.daikombat.dto.GetSer" +
      "verInfoCommandH\000\0221\n\013pingCommand\030\007 \001(\0132\032." +
      "daikombat.dto.PingCommandH\000\0227\n\016respawnCo" +
      "mmand\030\010 \001(\0132\035.daikombat.dto.RespawnComma" +
      "ndH\000\022K\n\030downloadMapAssetsCommand\030\n \001(\0132\'" +
      ".daikombat.dto.DownloadMapAssetsCommandH" +
      "\000B\t\n\007command\"\\\n\024GetServerInfoCommand\0224\n\013" +
      "playerClass\030\001 \001(\0162\032.daikombat.dto.Player" +
      "ClassH\000\210\001\001B\016\n\014_playerClass\"<\n\030DownloadMa" +
      "pAssetsCommand\022\024\n\007mapName\030\001 \001(\tH\000\210\001\001B\n\n\010" +
      "_mapName\"\r\n\013PingCommand\"\260\001\n\024PushChatEven" +
      "tCommand\022\023\n\006gameId\030\001 \001(\005H\000\210\001\001\022\024\n\007message" +
      "\030\002 \001(\tH\001\210\001\001\022\025\n\010playerId\030\003 \001(\005H\002\210\001\001\022(\n\005ta" +
      "unt\030\004 \001(\0162\024.daikombat.dto.TauntH\003\210\001\001B\t\n\007" +
      "_gameIdB\n\n\010_messageB\013\n\t_playerIdB\010\n\006_tau" +
      "nt\"\261\002\n\017JoinGameCommand\022\023\n\006gameId\030\001 \001(\005H\000" +
      "\210\001\001\022\024\n\007version\030\002 \001(\tH\001\210\001\001\022\027\n\nplayerName\030" +
      "\003 \001(\tH\002\210\001\001\0221\n\004skin\030\004 \001(\0162\036.daikombat.dto" +
      ".PlayerSkinColorH\003\210\001\001\022\035\n\020recoveryPlayerI" +
      "d\030\005 \001(\005H\004\210\001\001\0224\n\013playerClass\030\006 \001(\0162\032.daik" +
      "ombat.dto.PlayerClassH\005\210\001\001B\t\n\007_gameIdB\n\n" +
      "\010_versionB\r\n\013_playerNameB\007\n\005_skinB\023\n\021_re" +
      "coveryPlayerIdB\016\n\014_playerClass\"T\n\016Respaw" +
      "nCommand\022\023\n\006gameId\030\001 \001(\005H\000\210\001\001\022\025\n\010playerI" +
      "d\030\002 \001(\005H\001\210\001\001B\t\n\007_gameIdB\013\n\t_playerId\"\224\006\n" +
      "\024PushGameEventCommand\022\023\n\006gameId\030\001 \001(\005H\000\210" +
      "\001\001\022I\n\teventType\030\002 \001(\01621.daikombat.dto.Pu" +
      "shGameEventCommand.GameEventTypeH\001\210\001\001\022,\n" +
      "\010position\030\003 \001(\0132\025.daikombat.dto.VectorH\002" +
      "\210\001\001\022-\n\tdirection\030\004 \001(\0132\025.daikombat.dto.V" +
      "ectorH\003\210\001\001\022\025\n\010playerId\030\005 \001(\005H\004\210\001\001\022\035\n\020aff" +
      "ectedPlayerId\030\006 \001(\005H\005\210\001\001\022\025\n\010sequence\030\007 \001" +
      "(\005H\006\210\001\001\022\024\n\007pingMls\030\010 \001(\005H\007\210\001\001\022\027\n\ntelepor" +
      "tId\030\t \001(\005H\010\210\001\001\0222\n\nweaponType\030\n \001(\0162\031.dai" +
      "kombat.dto.WeaponTypeH\t\210\001\001\022=\n\nprojectile" +
      "\030\013 \001(\0132$.daikombat.dto.ProjectileCoordin" +
      "atesH\n\210\001\001\0224\n\007powerUp\030\014 \001(\0162\036.daikombat.d" +
      "to.GamePowerUpTypeH\013\210\001\001\022\030\n\013gameSession\030\r" +
      " \001(\005H\014\210\001\001\"H\n\rGameEventType\022\010\n\004MOVE\020\000\022\n\n\006" +
      "ATTACK\020\001\022\023\n\017POWER_UP_PICKUP\020\002\022\014\n\010TELEPOR" +
      "T\020\003B\t\n\007_gameIdB\014\n\n_eventTypeB\013\n\t_positio" +
      "nB\014\n\n_directionB\013\n\t_playerIdB\023\n\021_affecte" +
      "dPlayerIdB\013\n\t_sequenceB\n\n\010_pingMlsB\r\n\013_t" +
      "eleportIdB\r\n\013_weaponTypeB\r\n\013_projectileB" +
      "\n\n\010_powerUpB\016\n\014_gameSessionB&\n\"com.bever" +
      "ly.hills.money.gang.protoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.beverly.hills.money.gang.proto.ServerCommon.getDescriptor(),
        });
    internal_static_daikombat_dto_ServerCommand_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_daikombat_dto_ServerCommand_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_daikombat_dto_ServerCommand_descriptor,
        new java.lang.String[] { "ChatCommand", "GameCommand", "JoinGameCommand", "GetServerInfoCommand", "PingCommand", "RespawnCommand", "DownloadMapAssetsCommand", "Command", });
    internal_static_daikombat_dto_GetServerInfoCommand_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_daikombat_dto_GetServerInfoCommand_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_daikombat_dto_GetServerInfoCommand_descriptor,
        new java.lang.String[] { "PlayerClass", });
    internal_static_daikombat_dto_DownloadMapAssetsCommand_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_daikombat_dto_DownloadMapAssetsCommand_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_daikombat_dto_DownloadMapAssetsCommand_descriptor,
        new java.lang.String[] { "MapName", });
    internal_static_daikombat_dto_PingCommand_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_daikombat_dto_PingCommand_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_daikombat_dto_PingCommand_descriptor,
        new java.lang.String[] { });
    internal_static_daikombat_dto_PushChatEventCommand_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_daikombat_dto_PushChatEventCommand_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_daikombat_dto_PushChatEventCommand_descriptor,
        new java.lang.String[] { "GameId", "Message", "PlayerId", "Taunt", });
    internal_static_daikombat_dto_JoinGameCommand_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_daikombat_dto_JoinGameCommand_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_daikombat_dto_JoinGameCommand_descriptor,
        new java.lang.String[] { "GameId", "Version", "PlayerName", "Skin", "RecoveryPlayerId", "PlayerClass", });
    internal_static_daikombat_dto_RespawnCommand_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_daikombat_dto_RespawnCommand_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_daikombat_dto_RespawnCommand_descriptor,
        new java.lang.String[] { "GameId", "PlayerId", });
    internal_static_daikombat_dto_PushGameEventCommand_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_daikombat_dto_PushGameEventCommand_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_daikombat_dto_PushGameEventCommand_descriptor,
        new java.lang.String[] { "GameId", "EventType", "Position", "Direction", "PlayerId", "AffectedPlayerId", "Sequence", "PingMls", "TeleportId", "WeaponType", "Projectile", "PowerUp", "GameSession", });
    com.beverly.hills.money.gang.proto.ServerCommon.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
