// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: schema/src/main/resources/server-response.proto

// Protobuf Java Version: 3.25.0
package com.beverly.hills.money.gang.proto;

public final class ServerResponseOuterClass {
  private ServerResponseOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_daikombat_dto_ServerResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_daikombat_dto_ServerResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_daikombat_dto_ServerResponse_TeleportSpawnEvent_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_daikombat_dto_ServerResponse_TeleportSpawnEvent_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_daikombat_dto_ServerResponse_TeleportSpawnEventItem_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_daikombat_dto_ServerResponse_TeleportSpawnEventItem_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_daikombat_dto_ServerResponse_PowerUpSpawnEvent_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_daikombat_dto_ServerResponse_PowerUpSpawnEvent_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_daikombat_dto_ServerResponse_PowerUpSpawnEventItem_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_daikombat_dto_ServerResponse_PowerUpSpawnEventItem_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_daikombat_dto_ServerResponse_GameOver_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_daikombat_dto_ServerResponse_GameOver_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_daikombat_dto_ServerResponse_ServerInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_daikombat_dto_ServerResponse_ServerInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_daikombat_dto_ServerResponse_WeaponInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_daikombat_dto_ServerResponse_WeaponInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_daikombat_dto_ServerResponse_ProjectileInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_daikombat_dto_ServerResponse_ProjectileInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_daikombat_dto_ServerResponse_Ping_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_daikombat_dto_ServerResponse_Ping_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_daikombat_dto_ServerResponse_GameInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_daikombat_dto_ServerResponse_GameInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_daikombat_dto_ServerResponse_ErrorEvent_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_daikombat_dto_ServerResponse_ErrorEvent_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_daikombat_dto_ServerResponse_ChatEvents_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_daikombat_dto_ServerResponse_ChatEvents_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_daikombat_dto_ServerResponse_GameEvents_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_daikombat_dto_ServerResponse_GameEvents_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_daikombat_dto_ServerResponse_ChatEvent_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_daikombat_dto_ServerResponse_ChatEvent_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_daikombat_dto_ServerResponse_GameEvent_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_daikombat_dto_ServerResponse_GameEvent_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_daikombat_dto_ServerResponse_LeaderBoard_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_daikombat_dto_ServerResponse_LeaderBoard_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_daikombat_dto_ServerResponse_LeaderBoardItem_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_daikombat_dto_ServerResponse_LeaderBoardItem_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_daikombat_dto_ServerResponse_GameEventPlayerStats_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_daikombat_dto_ServerResponse_GameEventPlayerStats_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_daikombat_dto_ServerResponse_PlayerCurrentWeaponAmmo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_daikombat_dto_ServerResponse_PlayerCurrentWeaponAmmo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_daikombat_dto_ServerResponse_PlayerGameMatchStats_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_daikombat_dto_ServerResponse_PlayerGameMatchStats_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_daikombat_dto_ServerResponse_GamePowerUp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_daikombat_dto_ServerResponse_GamePowerUp_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n/schema/src/main/resources/server-respo" +
      "nse.proto\022\rdaikombat.dto\032-schema/src/mai" +
      "n/resources/server-common.proto\"\274%\n\016Serv" +
      "erResponse\022>\n\nerrorEvent\030\001 \001(\0132(.daikomb" +
      "at.dto.ServerResponse.ErrorEventH\000\022=\n\nch" +
      "atEvents\030\002 \001(\0132\'.daikombat.dto.ServerRes" +
      "ponse.ChatEventH\000\022>\n\ngameEvents\030\003 \001(\0132(." +
      "daikombat.dto.ServerResponse.GameEventsH" +
      "\000\022>\n\nserverInfo\030\004 \001(\0132(.daikombat.dto.Se" +
      "rverResponse.ServerInfoH\000\0222\n\004ping\030\005 \001(\0132" +
      "\".daikombat.dto.ServerResponse.PingH\000\022:\n" +
      "\010gameOver\030\006 \001(\0132&.daikombat.dto.ServerRe" +
      "sponse.GameOverH\000\022G\n\014powerUpSpawn\030\007 \001(\0132" +
      "/.daikombat.dto.ServerResponse.PowerUpSp" +
      "awnEventH\000\022I\n\rteleportSpawn\030\010 \001(\01320.daik" +
      "ombat.dto.ServerResponse.TeleportSpawnEv" +
      "entH\000\022-\n\tmapAssets\030\t \001(\0132\030.daikombat.dto" +
      ".MapAssetsH\000\032Y\n\022TeleportSpawnEvent\022C\n\005it" +
      "ems\030\001 \003(\01324.daikombat.dto.ServerResponse" +
      ".TeleportSpawnEventItem\032k\n\026TeleportSpawn" +
      "EventItem\022,\n\010position\030\001 \001(\0132\025.daikombat." +
      "dto.VectorH\000\210\001\001\022\017\n\002id\030\002 \001(\005H\001\210\001\001B\013\n\t_pos" +
      "itionB\005\n\003_id\032W\n\021PowerUpSpawnEvent\022B\n\005ite" +
      "ms\030\001 \003(\01323.daikombat.dto.ServerResponse." +
      "PowerUpSpawnEventItem\032\235\001\n\025PowerUpSpawnEv" +
      "entItem\022@\n\004type\030\001 \001(\0162-.daikombat.dto.Se" +
      "rverResponse.GamePowerUpTypeH\000\210\001\001\022,\n\010pos" +
      "ition\030\002 \001(\0132\025.daikombat.dto.VectorH\001\210\001\001B" +
      "\007\n\005_typeB\013\n\t_position\032_\n\010GameOver\022C\n\013lea" +
      "derBoard\030\001 \001(\0132).daikombat.dto.ServerRes" +
      "ponse.LeaderBoardH\000\210\001\001B\016\n\014_leaderBoard\032\305" +
      "\001\n\nServerInfo\0225\n\005games\030\001 \003(\0132&.daikombat" +
      ".dto.ServerResponse.GameInfo\022\024\n\007version\030" +
      "\002 \001(\tH\000\210\001\001\022\027\n\nfragsToWin\030\003 \001(\005H\001\210\001\001\022\037\n\022m" +
      "ovesUpdateFreqMls\030\004 \001(\005H\002\210\001\001B\n\n\010_version" +
      "B\r\n\013_fragsToWinB\025\n\023_movesUpdateFreqMls\032\277" +
      "\001\n\nWeaponInfo\0222\n\nweaponType\030\001 \001(\0162\031.daik" +
      "ombat.dto.WeaponTypeH\000\210\001\001\022\030\n\013maxDistance" +
      "\030\002 \001(\001H\001\210\001\001\022\025\n\010delayMls\030\003 \001(\005H\002\210\001\001\022\024\n\007ma" +
      "xAmmo\030\004 \001(\005H\003\210\001\001B\r\n\013_weaponTypeB\016\n\014_maxD" +
      "istanceB\013\n\t_delayMlsB\n\n\010_maxAmmo\032\177\n\016Proj" +
      "ectileInfo\022:\n\016projectileType\030\001 \001(\0162\035.dai" +
      "kombat.dto.ProjectileTypeH\000\210\001\001\022\023\n\006radius" +
      "\030\002 \001(\001H\001\210\001\001B\021\n\017_projectileTypeB\t\n\007_radiu" +
      "s\032\006\n\004Ping\032\363\003\n\010GameInfo\022\023\n\006gameId\030\001 \001(\005H\000" +
      "\210\001\001\022\032\n\rplayersOnline\030\002 \001(\005H\001\210\001\001\022\033\n\016maxGa" +
      "mePlayers\030\003 \001(\005H\002\210\001\001\022=\n\013weaponsInfo\030\005 \003(" +
      "\0132(.daikombat.dto.ServerResponse.WeaponI" +
      "nfo\022D\n\016projectileInfo\030\006 \003(\0132,.daikombat." +
      "dto.ServerResponse.ProjectileInfo\022\030\n\013pla" +
      "yerSpeed\030\007 \001(\002H\003\210\001\001\022\032\n\rmaxVisibility\030\010 \001" +
      "(\005H\004\210\001\001\022\022\n\005title\030\t \001(\tH\005\210\001\001\022\030\n\013descripti" +
      "on\030\n \001(\tH\006\210\001\001\0224\n\013mapMetadata\030\013 \001(\0132\032.dai" +
      "kombat.dto.MapMetadataH\007\210\001\001B\t\n\007_gameIdB\020" +
      "\n\016_playersOnlineB\021\n\017_maxGamePlayersB\016\n\014_" +
      "playerSpeedB\020\n\016_maxVisibilityB\010\n\006_titleB" +
      "\016\n\014_descriptionB\016\n\014_mapMetadata\032T\n\nError" +
      "Event\022\026\n\terrorCode\030\001 \001(\005H\000\210\001\001\022\024\n\007message" +
      "\030\002 \001(\tH\001\210\001\001B\014\n\n_errorCodeB\n\n\010_message\032E\n" +
      "\nChatEvents\0227\n\006events\030\001 \003(\0132\'.daikombat." +
      "dto.ServerResponse.ChatEvent\032s\n\nGameEven" +
      "ts\022\032\n\rplayersOnline\030\001 \001(\005H\000\210\001\001\0227\n\006events" +
      "\030\002 \003(\0132\'.daikombat.dto.ServerResponse.Ga" +
      "meEventB\020\n\016_playersOnline\032\241\001\n\tChatEvent\022" +
      "\025\n\010playerId\030\001 \001(\005H\000\210\001\001\022\024\n\007message\030\002 \001(\tH" +
      "\001\210\001\001\022\021\n\004name\030\003 \001(\tH\002\210\001\001\022(\n\005taunt\030\004 \001(\0162\024" +
      ".daikombat.dto.TauntH\003\210\001\001B\013\n\t_playerIdB\n" +
      "\n\010_messageB\007\n\005_nameB\010\n\006_taunt\032\224\005\n\tGameEv" +
      "ent\022G\n\006player\030\001 \001(\01322.daikombat.dto.Serv" +
      "erResponse.GameEventPlayerStatsH\000\210\001\001\022O\n\016" +
      "affectedPlayer\030\002 \001(\01322.daikombat.dto.Ser" +
      "verResponse.GameEventPlayerStatsH\001\210\001\001\022H\n" +
      "\teventType\030\003 \001(\01625.daikombat.dto.ServerR" +
      "esponse.GameEvent.GameEventType\022C\n\013leade" +
      "rBoard\030\004 \001(\0132).daikombat.dto.ServerRespo" +
      "nse.LeaderBoardH\002\210\001\001\022\025\n\010sequence\030\005 \001(\005H\003" +
      "\210\001\001\0222\n\nweaponType\030\006 \001(\0162\031.daikombat.dto." +
      "WeaponTypeH\004\210\001\001\022=\n\nprojectile\030\007 \001(\0132$.da" +
      "ikombat.dto.ProjectileCoordinatesH\005\210\001\001\"{" +
      "\n\rGameEventType\022\010\n\004MOVE\020\000\022\n\n\006ATTACK\020\001\022\020\n" +
      "\014GET_ATTACKED\020\002\022\010\n\004KILL\020\003\022\t\n\005SPAWN\020\004\022\010\n\004" +
      "EXIT\020\005\022\014\n\010TELEPORT\020\006\022\010\n\004JOIN\020\007\022\013\n\007RESPAW" +
      "N\020\010B\t\n\007_playerB\021\n\017_affectedPlayerB\016\n\014_le" +
      "aderBoardB\013\n\t_sequenceB\r\n\013_weaponTypeB\r\n" +
      "\013_projectile\032K\n\013LeaderBoard\022<\n\005items\030\001 \003" +
      "(\0132-.daikombat.dto.ServerResponse.Leader" +
      "BoardItem\032\311\002\n\017LeaderBoardItem\022\025\n\010playerI" +
      "d\030\001 \001(\005H\000\210\001\001\022\022\n\005kills\030\002 \001(\005H\001\210\001\001\022\027\n\nplay" +
      "erName\030\003 \001(\tH\002\210\001\001\022\023\n\006deaths\030\004 \001(\005H\003\210\001\001\022\024" +
      "\n\007pingMls\030\005 \001(\005H\004\210\001\001\0224\n\013playerClass\030\006 \001(" +
      "\0162\032.daikombat.dto.PlayerClassH\005\210\001\001\0226\n\tsk" +
      "inColor\030\007 \001(\0162\036.daikombat.dto.PlayerSkin" +
      "ColorH\006\210\001\001B\013\n\t_playerIdB\010\n\006_killsB\r\n\013_pl" +
      "ayerNameB\t\n\007_deathsB\n\n\010_pingMlsB\016\n\014_play" +
      "erClassB\014\n\n_skinColor\032\224\005\n\024GameEventPlaye" +
      "rStats\022\025\n\010playerId\030\001 \001(\005H\000\210\001\001\022\027\n\nplayerN" +
      "ame\030\002 \001(\tH\001\210\001\001\022\'\n\010position\030\003 \001(\0132\025.daiko" +
      "mbat.dto.Vector\022(\n\tdirection\030\004 \001(\0132\025.dai" +
      "kombat.dto.Vector\022\023\n\006health\030\005 \001(\005H\002\210\001\001\022A" +
      "\n\016activePowerUps\030\006 \003(\0132).daikombat.dto.S" +
      "erverResponse.GamePowerUp\0226\n\tskinColor\030\007" +
      " \001(\0162\036.daikombat.dto.PlayerSkinColorH\003\210\001" +
      "\001\022O\n\016gameMatchStats\030\010 \001(\01322.daikombat.dt" +
      "o.ServerResponse.PlayerGameMatchStatsH\004\210" +
      "\001\001\022\024\n\007pingMls\030\t \001(\005H\005\210\001\001\0224\n\013playerClass\030" +
      "\n \001(\0162\032.daikombat.dto.PlayerClassH\006\210\001\001\022\022" +
      "\n\005speed\030\013 \001(\002H\007\210\001\001\022J\n\013currentAmmo\030\014 \003(\0132" +
      "5.daikombat.dto.ServerResponse.PlayerCur" +
      "rentWeaponAmmoB\013\n\t_playerIdB\r\n\013_playerNa" +
      "meB\t\n\007_healthB\014\n\n_skinColorB\021\n\017_gameMatc" +
      "hStatsB\n\n\010_pingMlsB\016\n\014_playerClassB\010\n\006_s" +
      "peed\032p\n\027PlayerCurrentWeaponAmmo\022.\n\006weapo" +
      "n\030\001 \001(\0162\031.daikombat.dto.WeaponTypeH\000\210\001\001\022" +
      "\021\n\004ammo\030\002 \001(\005H\001\210\001\001B\t\n\007_weaponB\007\n\005_ammo\032T" +
      "\n\024PlayerGameMatchStats\022\022\n\005kills\030\001 \001(\005H\000\210" +
      "\001\001\022\023\n\006deaths\030\002 \001(\005H\001\210\001\001B\010\n\006_killsB\t\n\007_de" +
      "aths\032\202\001\n\013GamePowerUp\022@\n\004type\030\001 \001(\0162-.dai" +
      "kombat.dto.ServerResponse.GamePowerUpTyp" +
      "eH\000\210\001\001\022\030\n\013lastsForMls\030\002 \001(\005H\001\210\001\001B\007\n\005_typ" +
      "eB\016\n\014_lastsForMls\"w\n\017GamePowerUpType\022\017\n\013" +
      "QUAD_DAMAGE\020\000\022\020\n\014INVISIBILITY\020\001\022\013\n\007DEFEN" +
      "CE\020\002\022\n\n\006HEALTH\020\003\022\017\n\013MEDIUM_AMMO\020\004\022\014\n\010BIG" +
      "_AMMO\020\005\022\t\n\005BEAST\020\006B\n\n\010responseB&\n\"com.be" +
      "verly.hills.money.gang.protoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.beverly.hills.money.gang.proto.ServerCommon.getDescriptor(),
        });
    internal_static_daikombat_dto_ServerResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_daikombat_dto_ServerResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_daikombat_dto_ServerResponse_descriptor,
        new java.lang.String[] { "ErrorEvent", "ChatEvents", "GameEvents", "ServerInfo", "Ping", "GameOver", "PowerUpSpawn", "TeleportSpawn", "MapAssets", "Response", });
    internal_static_daikombat_dto_ServerResponse_TeleportSpawnEvent_descriptor =
      internal_static_daikombat_dto_ServerResponse_descriptor.getNestedTypes().get(0);
    internal_static_daikombat_dto_ServerResponse_TeleportSpawnEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_daikombat_dto_ServerResponse_TeleportSpawnEvent_descriptor,
        new java.lang.String[] { "Items", });
    internal_static_daikombat_dto_ServerResponse_TeleportSpawnEventItem_descriptor =
      internal_static_daikombat_dto_ServerResponse_descriptor.getNestedTypes().get(1);
    internal_static_daikombat_dto_ServerResponse_TeleportSpawnEventItem_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_daikombat_dto_ServerResponse_TeleportSpawnEventItem_descriptor,
        new java.lang.String[] { "Position", "Id", });
    internal_static_daikombat_dto_ServerResponse_PowerUpSpawnEvent_descriptor =
      internal_static_daikombat_dto_ServerResponse_descriptor.getNestedTypes().get(2);
    internal_static_daikombat_dto_ServerResponse_PowerUpSpawnEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_daikombat_dto_ServerResponse_PowerUpSpawnEvent_descriptor,
        new java.lang.String[] { "Items", });
    internal_static_daikombat_dto_ServerResponse_PowerUpSpawnEventItem_descriptor =
      internal_static_daikombat_dto_ServerResponse_descriptor.getNestedTypes().get(3);
    internal_static_daikombat_dto_ServerResponse_PowerUpSpawnEventItem_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_daikombat_dto_ServerResponse_PowerUpSpawnEventItem_descriptor,
        new java.lang.String[] { "Type", "Position", });
    internal_static_daikombat_dto_ServerResponse_GameOver_descriptor =
      internal_static_daikombat_dto_ServerResponse_descriptor.getNestedTypes().get(4);
    internal_static_daikombat_dto_ServerResponse_GameOver_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_daikombat_dto_ServerResponse_GameOver_descriptor,
        new java.lang.String[] { "LeaderBoard", });
    internal_static_daikombat_dto_ServerResponse_ServerInfo_descriptor =
      internal_static_daikombat_dto_ServerResponse_descriptor.getNestedTypes().get(5);
    internal_static_daikombat_dto_ServerResponse_ServerInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_daikombat_dto_ServerResponse_ServerInfo_descriptor,
        new java.lang.String[] { "Games", "Version", "FragsToWin", "MovesUpdateFreqMls", });
    internal_static_daikombat_dto_ServerResponse_WeaponInfo_descriptor =
      internal_static_daikombat_dto_ServerResponse_descriptor.getNestedTypes().get(6);
    internal_static_daikombat_dto_ServerResponse_WeaponInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_daikombat_dto_ServerResponse_WeaponInfo_descriptor,
        new java.lang.String[] { "WeaponType", "MaxDistance", "DelayMls", "MaxAmmo", });
    internal_static_daikombat_dto_ServerResponse_ProjectileInfo_descriptor =
      internal_static_daikombat_dto_ServerResponse_descriptor.getNestedTypes().get(7);
    internal_static_daikombat_dto_ServerResponse_ProjectileInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_daikombat_dto_ServerResponse_ProjectileInfo_descriptor,
        new java.lang.String[] { "ProjectileType", "Radius", });
    internal_static_daikombat_dto_ServerResponse_Ping_descriptor =
      internal_static_daikombat_dto_ServerResponse_descriptor.getNestedTypes().get(8);
    internal_static_daikombat_dto_ServerResponse_Ping_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_daikombat_dto_ServerResponse_Ping_descriptor,
        new java.lang.String[] { });
    internal_static_daikombat_dto_ServerResponse_GameInfo_descriptor =
      internal_static_daikombat_dto_ServerResponse_descriptor.getNestedTypes().get(9);
    internal_static_daikombat_dto_ServerResponse_GameInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_daikombat_dto_ServerResponse_GameInfo_descriptor,
        new java.lang.String[] { "GameId", "PlayersOnline", "MaxGamePlayers", "WeaponsInfo", "ProjectileInfo", "PlayerSpeed", "MaxVisibility", "Title", "Description", "MapMetadata", });
    internal_static_daikombat_dto_ServerResponse_ErrorEvent_descriptor =
      internal_static_daikombat_dto_ServerResponse_descriptor.getNestedTypes().get(10);
    internal_static_daikombat_dto_ServerResponse_ErrorEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_daikombat_dto_ServerResponse_ErrorEvent_descriptor,
        new java.lang.String[] { "ErrorCode", "Message", });
    internal_static_daikombat_dto_ServerResponse_ChatEvents_descriptor =
      internal_static_daikombat_dto_ServerResponse_descriptor.getNestedTypes().get(11);
    internal_static_daikombat_dto_ServerResponse_ChatEvents_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_daikombat_dto_ServerResponse_ChatEvents_descriptor,
        new java.lang.String[] { "Events", });
    internal_static_daikombat_dto_ServerResponse_GameEvents_descriptor =
      internal_static_daikombat_dto_ServerResponse_descriptor.getNestedTypes().get(12);
    internal_static_daikombat_dto_ServerResponse_GameEvents_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_daikombat_dto_ServerResponse_GameEvents_descriptor,
        new java.lang.String[] { "PlayersOnline", "Events", });
    internal_static_daikombat_dto_ServerResponse_ChatEvent_descriptor =
      internal_static_daikombat_dto_ServerResponse_descriptor.getNestedTypes().get(13);
    internal_static_daikombat_dto_ServerResponse_ChatEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_daikombat_dto_ServerResponse_ChatEvent_descriptor,
        new java.lang.String[] { "PlayerId", "Message", "Name", "Taunt", });
    internal_static_daikombat_dto_ServerResponse_GameEvent_descriptor =
      internal_static_daikombat_dto_ServerResponse_descriptor.getNestedTypes().get(14);
    internal_static_daikombat_dto_ServerResponse_GameEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_daikombat_dto_ServerResponse_GameEvent_descriptor,
        new java.lang.String[] { "Player", "AffectedPlayer", "EventType", "LeaderBoard", "Sequence", "WeaponType", "Projectile", });
    internal_static_daikombat_dto_ServerResponse_LeaderBoard_descriptor =
      internal_static_daikombat_dto_ServerResponse_descriptor.getNestedTypes().get(15);
    internal_static_daikombat_dto_ServerResponse_LeaderBoard_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_daikombat_dto_ServerResponse_LeaderBoard_descriptor,
        new java.lang.String[] { "Items", });
    internal_static_daikombat_dto_ServerResponse_LeaderBoardItem_descriptor =
      internal_static_daikombat_dto_ServerResponse_descriptor.getNestedTypes().get(16);
    internal_static_daikombat_dto_ServerResponse_LeaderBoardItem_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_daikombat_dto_ServerResponse_LeaderBoardItem_descriptor,
        new java.lang.String[] { "PlayerId", "Kills", "PlayerName", "Deaths", "PingMls", "PlayerClass", "SkinColor", });
    internal_static_daikombat_dto_ServerResponse_GameEventPlayerStats_descriptor =
      internal_static_daikombat_dto_ServerResponse_descriptor.getNestedTypes().get(17);
    internal_static_daikombat_dto_ServerResponse_GameEventPlayerStats_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_daikombat_dto_ServerResponse_GameEventPlayerStats_descriptor,
        new java.lang.String[] { "PlayerId", "PlayerName", "Position", "Direction", "Health", "ActivePowerUps", "SkinColor", "GameMatchStats", "PingMls", "PlayerClass", "Speed", "CurrentAmmo", });
    internal_static_daikombat_dto_ServerResponse_PlayerCurrentWeaponAmmo_descriptor =
      internal_static_daikombat_dto_ServerResponse_descriptor.getNestedTypes().get(18);
    internal_static_daikombat_dto_ServerResponse_PlayerCurrentWeaponAmmo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_daikombat_dto_ServerResponse_PlayerCurrentWeaponAmmo_descriptor,
        new java.lang.String[] { "Weapon", "Ammo", });
    internal_static_daikombat_dto_ServerResponse_PlayerGameMatchStats_descriptor =
      internal_static_daikombat_dto_ServerResponse_descriptor.getNestedTypes().get(19);
    internal_static_daikombat_dto_ServerResponse_PlayerGameMatchStats_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_daikombat_dto_ServerResponse_PlayerGameMatchStats_descriptor,
        new java.lang.String[] { "Kills", "Deaths", });
    internal_static_daikombat_dto_ServerResponse_GamePowerUp_descriptor =
      internal_static_daikombat_dto_ServerResponse_descriptor.getNestedTypes().get(20);
    internal_static_daikombat_dto_ServerResponse_GamePowerUp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_daikombat_dto_ServerResponse_GamePowerUp_descriptor,
        new java.lang.String[] { "Type", "LastsForMls", });
    com.beverly.hills.money.gang.proto.ServerCommon.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
