// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: schema/src/main/resources/server-common.proto

// Protobuf Java Version: 3.25.0
package com.beverly.hills.money.gang.proto;

public interface VectorOrBuilder extends
    // @@protoc_insertion_point(interface_extends:daikombat.dto.Vector)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional float x = 1;</code>
   * @return Whether the x field is set.
   */
  boolean hasX();
  /**
   * <code>optional float x = 1;</code>
   * @return The x.
   */
  float getX();

  /**
   * <code>optional float y = 2;</code>
   * @return Whether the y field is set.
   */
  boolean hasY();
  /**
   * <code>optional float y = 2;</code>
   * @return The y.
   */
  float getY();
}
