// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/proto/server-commands.proto

// Protobuf Java Version: 3.25.0
package com.beverly.hills.money.gang.proto;

public interface PushGameEventCommandOrBuilder extends
    // @@protoc_insertion_point(interface_extends:daikombat.dto.PushGameEventCommand)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.daikombat.dto.PushGameEventCommand.GameEventType eventType = 1;</code>
   * @return The enum numeric value on the wire for eventType.
   */
  int getEventTypeValue();
  /**
   * <code>.daikombat.dto.PushGameEventCommand.GameEventType eventType = 1;</code>
   * @return The eventType.
   */
  com.beverly.hills.money.gang.proto.PushGameEventCommand.GameEventType getEventType();

  /**
   * <code>.daikombat.dto.PushGameEventCommand.Vector position = 2;</code>
   * @return Whether the position field is set.
   */
  boolean hasPosition();
  /**
   * <code>.daikombat.dto.PushGameEventCommand.Vector position = 2;</code>
   * @return The position.
   */
  com.beverly.hills.money.gang.proto.PushGameEventCommand.Vector getPosition();
  /**
   * <code>.daikombat.dto.PushGameEventCommand.Vector position = 2;</code>
   */
  com.beverly.hills.money.gang.proto.PushGameEventCommand.VectorOrBuilder getPositionOrBuilder();

  /**
   * <code>.daikombat.dto.PushGameEventCommand.Vector direction = 3;</code>
   * @return Whether the direction field is set.
   */
  boolean hasDirection();
  /**
   * <code>.daikombat.dto.PushGameEventCommand.Vector direction = 3;</code>
   * @return The direction.
   */
  com.beverly.hills.money.gang.proto.PushGameEventCommand.Vector getDirection();
  /**
   * <code>.daikombat.dto.PushGameEventCommand.Vector direction = 3;</code>
   */
  com.beverly.hills.money.gang.proto.PushGameEventCommand.VectorOrBuilder getDirectionOrBuilder();
}
