// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/proto/server-commands.proto

// Protobuf Java Version: 3.25.0
package com.beverly.hills.money.gang.proto;

/**
 * Protobuf type {@code daikombat.dto.PushGameEventCommand}
 */
public final class PushGameEventCommand extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:daikombat.dto.PushGameEventCommand)
    PushGameEventCommandOrBuilder {
private static final long serialVersionUID = 0L;
  // Use PushGameEventCommand.newBuilder() to construct.
  private PushGameEventCommand(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private PushGameEventCommand() {
    eventType_ = 0;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new PushGameEventCommand();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.beverly.hills.money.gang.proto.ServerCommands.internal_static_daikombat_dto_PushGameEventCommand_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.beverly.hills.money.gang.proto.ServerCommands.internal_static_daikombat_dto_PushGameEventCommand_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.beverly.hills.money.gang.proto.PushGameEventCommand.class, com.beverly.hills.money.gang.proto.PushGameEventCommand.Builder.class);
  }

  /**
   * Protobuf enum {@code daikombat.dto.PushGameEventCommand.GameEventType}
   */
  public enum GameEventType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>MOVE = 0;</code>
     */
    MOVE(0),
    /**
     * <code>SHOOT = 1;</code>
     */
    SHOOT(1),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>MOVE = 0;</code>
     */
    public static final int MOVE_VALUE = 0;
    /**
     * <code>SHOOT = 1;</code>
     */
    public static final int SHOOT_VALUE = 1;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static GameEventType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static GameEventType forNumber(int value) {
      switch (value) {
        case 0: return MOVE;
        case 1: return SHOOT;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<GameEventType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        GameEventType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<GameEventType>() {
            public GameEventType findValueByNumber(int number) {
              return GameEventType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.beverly.hills.money.gang.proto.PushGameEventCommand.getDescriptor().getEnumTypes().get(0);
    }

    private static final GameEventType[] VALUES = values();

    public static GameEventType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private GameEventType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:daikombat.dto.PushGameEventCommand.GameEventType)
  }

  public interface VectorOrBuilder extends
      // @@protoc_insertion_point(interface_extends:daikombat.dto.PushGameEventCommand.Vector)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>float x = 1;</code>
     * @return The x.
     */
    float getX();

    /**
     * <code>float y = 2;</code>
     * @return The y.
     */
    float getY();
  }
  /**
   * Protobuf type {@code daikombat.dto.PushGameEventCommand.Vector}
   */
  public static final class Vector extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:daikombat.dto.PushGameEventCommand.Vector)
      VectorOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Vector.newBuilder() to construct.
    private Vector(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Vector() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Vector();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.beverly.hills.money.gang.proto.ServerCommands.internal_static_daikombat_dto_PushGameEventCommand_Vector_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.beverly.hills.money.gang.proto.ServerCommands.internal_static_daikombat_dto_PushGameEventCommand_Vector_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.beverly.hills.money.gang.proto.PushGameEventCommand.Vector.class, com.beverly.hills.money.gang.proto.PushGameEventCommand.Vector.Builder.class);
    }

    public static final int X_FIELD_NUMBER = 1;
    private float x_ = 0F;
    /**
     * <code>float x = 1;</code>
     * @return The x.
     */
    @java.lang.Override
    public float getX() {
      return x_;
    }

    public static final int Y_FIELD_NUMBER = 2;
    private float y_ = 0F;
    /**
     * <code>float y = 2;</code>
     * @return The y.
     */
    @java.lang.Override
    public float getY() {
      return y_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (java.lang.Float.floatToRawIntBits(x_) != 0) {
        output.writeFloat(1, x_);
      }
      if (java.lang.Float.floatToRawIntBits(y_) != 0) {
        output.writeFloat(2, y_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (java.lang.Float.floatToRawIntBits(x_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(1, x_);
      }
      if (java.lang.Float.floatToRawIntBits(y_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(2, y_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.beverly.hills.money.gang.proto.PushGameEventCommand.Vector)) {
        return super.equals(obj);
      }
      com.beverly.hills.money.gang.proto.PushGameEventCommand.Vector other = (com.beverly.hills.money.gang.proto.PushGameEventCommand.Vector) obj;

      if (java.lang.Float.floatToIntBits(getX())
          != java.lang.Float.floatToIntBits(
              other.getX())) return false;
      if (java.lang.Float.floatToIntBits(getY())
          != java.lang.Float.floatToIntBits(
              other.getY())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + X_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getX());
      hash = (37 * hash) + Y_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getY());
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.beverly.hills.money.gang.proto.PushGameEventCommand.Vector parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.beverly.hills.money.gang.proto.PushGameEventCommand.Vector parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.beverly.hills.money.gang.proto.PushGameEventCommand.Vector parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.beverly.hills.money.gang.proto.PushGameEventCommand.Vector parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.beverly.hills.money.gang.proto.PushGameEventCommand.Vector parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.beverly.hills.money.gang.proto.PushGameEventCommand.Vector parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.beverly.hills.money.gang.proto.PushGameEventCommand.Vector parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.beverly.hills.money.gang.proto.PushGameEventCommand.Vector parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.beverly.hills.money.gang.proto.PushGameEventCommand.Vector parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.beverly.hills.money.gang.proto.PushGameEventCommand.Vector parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.beverly.hills.money.gang.proto.PushGameEventCommand.Vector parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.beverly.hills.money.gang.proto.PushGameEventCommand.Vector parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.beverly.hills.money.gang.proto.PushGameEventCommand.Vector prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code daikombat.dto.PushGameEventCommand.Vector}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:daikombat.dto.PushGameEventCommand.Vector)
        com.beverly.hills.money.gang.proto.PushGameEventCommand.VectorOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.beverly.hills.money.gang.proto.ServerCommands.internal_static_daikombat_dto_PushGameEventCommand_Vector_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.beverly.hills.money.gang.proto.ServerCommands.internal_static_daikombat_dto_PushGameEventCommand_Vector_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.beverly.hills.money.gang.proto.PushGameEventCommand.Vector.class, com.beverly.hills.money.gang.proto.PushGameEventCommand.Vector.Builder.class);
      }

      // Construct using com.beverly.hills.money.gang.proto.PushGameEventCommand.Vector.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        x_ = 0F;
        y_ = 0F;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.beverly.hills.money.gang.proto.ServerCommands.internal_static_daikombat_dto_PushGameEventCommand_Vector_descriptor;
      }

      @java.lang.Override
      public com.beverly.hills.money.gang.proto.PushGameEventCommand.Vector getDefaultInstanceForType() {
        return com.beverly.hills.money.gang.proto.PushGameEventCommand.Vector.getDefaultInstance();
      }

      @java.lang.Override
      public com.beverly.hills.money.gang.proto.PushGameEventCommand.Vector build() {
        com.beverly.hills.money.gang.proto.PushGameEventCommand.Vector result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.beverly.hills.money.gang.proto.PushGameEventCommand.Vector buildPartial() {
        com.beverly.hills.money.gang.proto.PushGameEventCommand.Vector result = new com.beverly.hills.money.gang.proto.PushGameEventCommand.Vector(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.beverly.hills.money.gang.proto.PushGameEventCommand.Vector result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.x_ = x_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.y_ = y_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.beverly.hills.money.gang.proto.PushGameEventCommand.Vector) {
          return mergeFrom((com.beverly.hills.money.gang.proto.PushGameEventCommand.Vector)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.beverly.hills.money.gang.proto.PushGameEventCommand.Vector other) {
        if (other == com.beverly.hills.money.gang.proto.PushGameEventCommand.Vector.getDefaultInstance()) return this;
        if (other.getX() != 0F) {
          setX(other.getX());
        }
        if (other.getY() != 0F) {
          setY(other.getY());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 13: {
                x_ = input.readFloat();
                bitField0_ |= 0x00000001;
                break;
              } // case 13
              case 21: {
                y_ = input.readFloat();
                bitField0_ |= 0x00000002;
                break;
              } // case 21
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private float x_ ;
      /**
       * <code>float x = 1;</code>
       * @return The x.
       */
      @java.lang.Override
      public float getX() {
        return x_;
      }
      /**
       * <code>float x = 1;</code>
       * @param value The x to set.
       * @return This builder for chaining.
       */
      public Builder setX(float value) {

        x_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>float x = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearX() {
        bitField0_ = (bitField0_ & ~0x00000001);
        x_ = 0F;
        onChanged();
        return this;
      }

      private float y_ ;
      /**
       * <code>float y = 2;</code>
       * @return The y.
       */
      @java.lang.Override
      public float getY() {
        return y_;
      }
      /**
       * <code>float y = 2;</code>
       * @param value The y to set.
       * @return This builder for chaining.
       */
      public Builder setY(float value) {

        y_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>float y = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearY() {
        bitField0_ = (bitField0_ & ~0x00000002);
        y_ = 0F;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:daikombat.dto.PushGameEventCommand.Vector)
    }

    // @@protoc_insertion_point(class_scope:daikombat.dto.PushGameEventCommand.Vector)
    private static final com.beverly.hills.money.gang.proto.PushGameEventCommand.Vector DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.beverly.hills.money.gang.proto.PushGameEventCommand.Vector();
    }

    public static com.beverly.hills.money.gang.proto.PushGameEventCommand.Vector getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Vector>
        PARSER = new com.google.protobuf.AbstractParser<Vector>() {
      @java.lang.Override
      public Vector parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Vector> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Vector> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.beverly.hills.money.gang.proto.PushGameEventCommand.Vector getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private int bitField0_;
  public static final int EVENTTYPE_FIELD_NUMBER = 1;
  private int eventType_ = 0;
  /**
   * <code>.daikombat.dto.PushGameEventCommand.GameEventType eventType = 1;</code>
   * @return The enum numeric value on the wire for eventType.
   */
  @java.lang.Override public int getEventTypeValue() {
    return eventType_;
  }
  /**
   * <code>.daikombat.dto.PushGameEventCommand.GameEventType eventType = 1;</code>
   * @return The eventType.
   */
  @java.lang.Override public com.beverly.hills.money.gang.proto.PushGameEventCommand.GameEventType getEventType() {
    com.beverly.hills.money.gang.proto.PushGameEventCommand.GameEventType result = com.beverly.hills.money.gang.proto.PushGameEventCommand.GameEventType.forNumber(eventType_);
    return result == null ? com.beverly.hills.money.gang.proto.PushGameEventCommand.GameEventType.UNRECOGNIZED : result;
  }

  public static final int POSITION_FIELD_NUMBER = 2;
  private com.beverly.hills.money.gang.proto.PushGameEventCommand.Vector position_;
  /**
   * <code>.daikombat.dto.PushGameEventCommand.Vector position = 2;</code>
   * @return Whether the position field is set.
   */
  @java.lang.Override
  public boolean hasPosition() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.daikombat.dto.PushGameEventCommand.Vector position = 2;</code>
   * @return The position.
   */
  @java.lang.Override
  public com.beverly.hills.money.gang.proto.PushGameEventCommand.Vector getPosition() {
    return position_ == null ? com.beverly.hills.money.gang.proto.PushGameEventCommand.Vector.getDefaultInstance() : position_;
  }
  /**
   * <code>.daikombat.dto.PushGameEventCommand.Vector position = 2;</code>
   */
  @java.lang.Override
  public com.beverly.hills.money.gang.proto.PushGameEventCommand.VectorOrBuilder getPositionOrBuilder() {
    return position_ == null ? com.beverly.hills.money.gang.proto.PushGameEventCommand.Vector.getDefaultInstance() : position_;
  }

  public static final int DIRECTION_FIELD_NUMBER = 3;
  private com.beverly.hills.money.gang.proto.PushGameEventCommand.Vector direction_;
  /**
   * <code>.daikombat.dto.PushGameEventCommand.Vector direction = 3;</code>
   * @return Whether the direction field is set.
   */
  @java.lang.Override
  public boolean hasDirection() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>.daikombat.dto.PushGameEventCommand.Vector direction = 3;</code>
   * @return The direction.
   */
  @java.lang.Override
  public com.beverly.hills.money.gang.proto.PushGameEventCommand.Vector getDirection() {
    return direction_ == null ? com.beverly.hills.money.gang.proto.PushGameEventCommand.Vector.getDefaultInstance() : direction_;
  }
  /**
   * <code>.daikombat.dto.PushGameEventCommand.Vector direction = 3;</code>
   */
  @java.lang.Override
  public com.beverly.hills.money.gang.proto.PushGameEventCommand.VectorOrBuilder getDirectionOrBuilder() {
    return direction_ == null ? com.beverly.hills.money.gang.proto.PushGameEventCommand.Vector.getDefaultInstance() : direction_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (eventType_ != com.beverly.hills.money.gang.proto.PushGameEventCommand.GameEventType.MOVE.getNumber()) {
      output.writeEnum(1, eventType_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(2, getPosition());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeMessage(3, getDirection());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (eventType_ != com.beverly.hills.money.gang.proto.PushGameEventCommand.GameEventType.MOVE.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, eventType_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getPosition());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getDirection());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.beverly.hills.money.gang.proto.PushGameEventCommand)) {
      return super.equals(obj);
    }
    com.beverly.hills.money.gang.proto.PushGameEventCommand other = (com.beverly.hills.money.gang.proto.PushGameEventCommand) obj;

    if (eventType_ != other.eventType_) return false;
    if (hasPosition() != other.hasPosition()) return false;
    if (hasPosition()) {
      if (!getPosition()
          .equals(other.getPosition())) return false;
    }
    if (hasDirection() != other.hasDirection()) return false;
    if (hasDirection()) {
      if (!getDirection()
          .equals(other.getDirection())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + EVENTTYPE_FIELD_NUMBER;
    hash = (53 * hash) + eventType_;
    if (hasPosition()) {
      hash = (37 * hash) + POSITION_FIELD_NUMBER;
      hash = (53 * hash) + getPosition().hashCode();
    }
    if (hasDirection()) {
      hash = (37 * hash) + DIRECTION_FIELD_NUMBER;
      hash = (53 * hash) + getDirection().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.beverly.hills.money.gang.proto.PushGameEventCommand parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.beverly.hills.money.gang.proto.PushGameEventCommand parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.beverly.hills.money.gang.proto.PushGameEventCommand parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.beverly.hills.money.gang.proto.PushGameEventCommand parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.beverly.hills.money.gang.proto.PushGameEventCommand parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.beverly.hills.money.gang.proto.PushGameEventCommand parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.beverly.hills.money.gang.proto.PushGameEventCommand parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.beverly.hills.money.gang.proto.PushGameEventCommand parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.beverly.hills.money.gang.proto.PushGameEventCommand parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.beverly.hills.money.gang.proto.PushGameEventCommand parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.beverly.hills.money.gang.proto.PushGameEventCommand parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.beverly.hills.money.gang.proto.PushGameEventCommand parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.beverly.hills.money.gang.proto.PushGameEventCommand prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code daikombat.dto.PushGameEventCommand}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:daikombat.dto.PushGameEventCommand)
      com.beverly.hills.money.gang.proto.PushGameEventCommandOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.beverly.hills.money.gang.proto.ServerCommands.internal_static_daikombat_dto_PushGameEventCommand_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.beverly.hills.money.gang.proto.ServerCommands.internal_static_daikombat_dto_PushGameEventCommand_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.beverly.hills.money.gang.proto.PushGameEventCommand.class, com.beverly.hills.money.gang.proto.PushGameEventCommand.Builder.class);
    }

    // Construct using com.beverly.hills.money.gang.proto.PushGameEventCommand.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getPositionFieldBuilder();
        getDirectionFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      eventType_ = 0;
      position_ = null;
      if (positionBuilder_ != null) {
        positionBuilder_.dispose();
        positionBuilder_ = null;
      }
      direction_ = null;
      if (directionBuilder_ != null) {
        directionBuilder_.dispose();
        directionBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.beverly.hills.money.gang.proto.ServerCommands.internal_static_daikombat_dto_PushGameEventCommand_descriptor;
    }

    @java.lang.Override
    public com.beverly.hills.money.gang.proto.PushGameEventCommand getDefaultInstanceForType() {
      return com.beverly.hills.money.gang.proto.PushGameEventCommand.getDefaultInstance();
    }

    @java.lang.Override
    public com.beverly.hills.money.gang.proto.PushGameEventCommand build() {
      com.beverly.hills.money.gang.proto.PushGameEventCommand result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.beverly.hills.money.gang.proto.PushGameEventCommand buildPartial() {
      com.beverly.hills.money.gang.proto.PushGameEventCommand result = new com.beverly.hills.money.gang.proto.PushGameEventCommand(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.beverly.hills.money.gang.proto.PushGameEventCommand result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.eventType_ = eventType_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.position_ = positionBuilder_ == null
            ? position_
            : positionBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.direction_ = directionBuilder_ == null
            ? direction_
            : directionBuilder_.build();
        to_bitField0_ |= 0x00000002;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.beverly.hills.money.gang.proto.PushGameEventCommand) {
        return mergeFrom((com.beverly.hills.money.gang.proto.PushGameEventCommand)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.beverly.hills.money.gang.proto.PushGameEventCommand other) {
      if (other == com.beverly.hills.money.gang.proto.PushGameEventCommand.getDefaultInstance()) return this;
      if (other.eventType_ != 0) {
        setEventTypeValue(other.getEventTypeValue());
      }
      if (other.hasPosition()) {
        mergePosition(other.getPosition());
      }
      if (other.hasDirection()) {
        mergeDirection(other.getDirection());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              eventType_ = input.readEnum();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 18: {
              input.readMessage(
                  getPositionFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              input.readMessage(
                  getDirectionFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int eventType_ = 0;
    /**
     * <code>.daikombat.dto.PushGameEventCommand.GameEventType eventType = 1;</code>
     * @return The enum numeric value on the wire for eventType.
     */
    @java.lang.Override public int getEventTypeValue() {
      return eventType_;
    }
    /**
     * <code>.daikombat.dto.PushGameEventCommand.GameEventType eventType = 1;</code>
     * @param value The enum numeric value on the wire for eventType to set.
     * @return This builder for chaining.
     */
    public Builder setEventTypeValue(int value) {
      eventType_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.daikombat.dto.PushGameEventCommand.GameEventType eventType = 1;</code>
     * @return The eventType.
     */
    @java.lang.Override
    public com.beverly.hills.money.gang.proto.PushGameEventCommand.GameEventType getEventType() {
      com.beverly.hills.money.gang.proto.PushGameEventCommand.GameEventType result = com.beverly.hills.money.gang.proto.PushGameEventCommand.GameEventType.forNumber(eventType_);
      return result == null ? com.beverly.hills.money.gang.proto.PushGameEventCommand.GameEventType.UNRECOGNIZED : result;
    }
    /**
     * <code>.daikombat.dto.PushGameEventCommand.GameEventType eventType = 1;</code>
     * @param value The eventType to set.
     * @return This builder for chaining.
     */
    public Builder setEventType(com.beverly.hills.money.gang.proto.PushGameEventCommand.GameEventType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000001;
      eventType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.daikombat.dto.PushGameEventCommand.GameEventType eventType = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearEventType() {
      bitField0_ = (bitField0_ & ~0x00000001);
      eventType_ = 0;
      onChanged();
      return this;
    }

    private com.beverly.hills.money.gang.proto.PushGameEventCommand.Vector position_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.beverly.hills.money.gang.proto.PushGameEventCommand.Vector, com.beverly.hills.money.gang.proto.PushGameEventCommand.Vector.Builder, com.beverly.hills.money.gang.proto.PushGameEventCommand.VectorOrBuilder> positionBuilder_;
    /**
     * <code>.daikombat.dto.PushGameEventCommand.Vector position = 2;</code>
     * @return Whether the position field is set.
     */
    public boolean hasPosition() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>.daikombat.dto.PushGameEventCommand.Vector position = 2;</code>
     * @return The position.
     */
    public com.beverly.hills.money.gang.proto.PushGameEventCommand.Vector getPosition() {
      if (positionBuilder_ == null) {
        return position_ == null ? com.beverly.hills.money.gang.proto.PushGameEventCommand.Vector.getDefaultInstance() : position_;
      } else {
        return positionBuilder_.getMessage();
      }
    }
    /**
     * <code>.daikombat.dto.PushGameEventCommand.Vector position = 2;</code>
     */
    public Builder setPosition(com.beverly.hills.money.gang.proto.PushGameEventCommand.Vector value) {
      if (positionBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        position_ = value;
      } else {
        positionBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.daikombat.dto.PushGameEventCommand.Vector position = 2;</code>
     */
    public Builder setPosition(
        com.beverly.hills.money.gang.proto.PushGameEventCommand.Vector.Builder builderForValue) {
      if (positionBuilder_ == null) {
        position_ = builderForValue.build();
      } else {
        positionBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.daikombat.dto.PushGameEventCommand.Vector position = 2;</code>
     */
    public Builder mergePosition(com.beverly.hills.money.gang.proto.PushGameEventCommand.Vector value) {
      if (positionBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
          position_ != null &&
          position_ != com.beverly.hills.money.gang.proto.PushGameEventCommand.Vector.getDefaultInstance()) {
          getPositionBuilder().mergeFrom(value);
        } else {
          position_ = value;
        }
      } else {
        positionBuilder_.mergeFrom(value);
      }
      if (position_ != null) {
        bitField0_ |= 0x00000002;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.daikombat.dto.PushGameEventCommand.Vector position = 2;</code>
     */
    public Builder clearPosition() {
      bitField0_ = (bitField0_ & ~0x00000002);
      position_ = null;
      if (positionBuilder_ != null) {
        positionBuilder_.dispose();
        positionBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.daikombat.dto.PushGameEventCommand.Vector position = 2;</code>
     */
    public com.beverly.hills.money.gang.proto.PushGameEventCommand.Vector.Builder getPositionBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return getPositionFieldBuilder().getBuilder();
    }
    /**
     * <code>.daikombat.dto.PushGameEventCommand.Vector position = 2;</code>
     */
    public com.beverly.hills.money.gang.proto.PushGameEventCommand.VectorOrBuilder getPositionOrBuilder() {
      if (positionBuilder_ != null) {
        return positionBuilder_.getMessageOrBuilder();
      } else {
        return position_ == null ?
            com.beverly.hills.money.gang.proto.PushGameEventCommand.Vector.getDefaultInstance() : position_;
      }
    }
    /**
     * <code>.daikombat.dto.PushGameEventCommand.Vector position = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.beverly.hills.money.gang.proto.PushGameEventCommand.Vector, com.beverly.hills.money.gang.proto.PushGameEventCommand.Vector.Builder, com.beverly.hills.money.gang.proto.PushGameEventCommand.VectorOrBuilder> 
        getPositionFieldBuilder() {
      if (positionBuilder_ == null) {
        positionBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.beverly.hills.money.gang.proto.PushGameEventCommand.Vector, com.beverly.hills.money.gang.proto.PushGameEventCommand.Vector.Builder, com.beverly.hills.money.gang.proto.PushGameEventCommand.VectorOrBuilder>(
                getPosition(),
                getParentForChildren(),
                isClean());
        position_ = null;
      }
      return positionBuilder_;
    }

    private com.beverly.hills.money.gang.proto.PushGameEventCommand.Vector direction_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.beverly.hills.money.gang.proto.PushGameEventCommand.Vector, com.beverly.hills.money.gang.proto.PushGameEventCommand.Vector.Builder, com.beverly.hills.money.gang.proto.PushGameEventCommand.VectorOrBuilder> directionBuilder_;
    /**
     * <code>.daikombat.dto.PushGameEventCommand.Vector direction = 3;</code>
     * @return Whether the direction field is set.
     */
    public boolean hasDirection() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>.daikombat.dto.PushGameEventCommand.Vector direction = 3;</code>
     * @return The direction.
     */
    public com.beverly.hills.money.gang.proto.PushGameEventCommand.Vector getDirection() {
      if (directionBuilder_ == null) {
        return direction_ == null ? com.beverly.hills.money.gang.proto.PushGameEventCommand.Vector.getDefaultInstance() : direction_;
      } else {
        return directionBuilder_.getMessage();
      }
    }
    /**
     * <code>.daikombat.dto.PushGameEventCommand.Vector direction = 3;</code>
     */
    public Builder setDirection(com.beverly.hills.money.gang.proto.PushGameEventCommand.Vector value) {
      if (directionBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        direction_ = value;
      } else {
        directionBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.daikombat.dto.PushGameEventCommand.Vector direction = 3;</code>
     */
    public Builder setDirection(
        com.beverly.hills.money.gang.proto.PushGameEventCommand.Vector.Builder builderForValue) {
      if (directionBuilder_ == null) {
        direction_ = builderForValue.build();
      } else {
        directionBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.daikombat.dto.PushGameEventCommand.Vector direction = 3;</code>
     */
    public Builder mergeDirection(com.beverly.hills.money.gang.proto.PushGameEventCommand.Vector value) {
      if (directionBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0) &&
          direction_ != null &&
          direction_ != com.beverly.hills.money.gang.proto.PushGameEventCommand.Vector.getDefaultInstance()) {
          getDirectionBuilder().mergeFrom(value);
        } else {
          direction_ = value;
        }
      } else {
        directionBuilder_.mergeFrom(value);
      }
      if (direction_ != null) {
        bitField0_ |= 0x00000004;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.daikombat.dto.PushGameEventCommand.Vector direction = 3;</code>
     */
    public Builder clearDirection() {
      bitField0_ = (bitField0_ & ~0x00000004);
      direction_ = null;
      if (directionBuilder_ != null) {
        directionBuilder_.dispose();
        directionBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.daikombat.dto.PushGameEventCommand.Vector direction = 3;</code>
     */
    public com.beverly.hills.money.gang.proto.PushGameEventCommand.Vector.Builder getDirectionBuilder() {
      bitField0_ |= 0x00000004;
      onChanged();
      return getDirectionFieldBuilder().getBuilder();
    }
    /**
     * <code>.daikombat.dto.PushGameEventCommand.Vector direction = 3;</code>
     */
    public com.beverly.hills.money.gang.proto.PushGameEventCommand.VectorOrBuilder getDirectionOrBuilder() {
      if (directionBuilder_ != null) {
        return directionBuilder_.getMessageOrBuilder();
      } else {
        return direction_ == null ?
            com.beverly.hills.money.gang.proto.PushGameEventCommand.Vector.getDefaultInstance() : direction_;
      }
    }
    /**
     * <code>.daikombat.dto.PushGameEventCommand.Vector direction = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.beverly.hills.money.gang.proto.PushGameEventCommand.Vector, com.beverly.hills.money.gang.proto.PushGameEventCommand.Vector.Builder, com.beverly.hills.money.gang.proto.PushGameEventCommand.VectorOrBuilder> 
        getDirectionFieldBuilder() {
      if (directionBuilder_ == null) {
        directionBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.beverly.hills.money.gang.proto.PushGameEventCommand.Vector, com.beverly.hills.money.gang.proto.PushGameEventCommand.Vector.Builder, com.beverly.hills.money.gang.proto.PushGameEventCommand.VectorOrBuilder>(
                getDirection(),
                getParentForChildren(),
                isClean());
        direction_ = null;
      }
      return directionBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:daikombat.dto.PushGameEventCommand)
  }

  // @@protoc_insertion_point(class_scope:daikombat.dto.PushGameEventCommand)
  private static final com.beverly.hills.money.gang.proto.PushGameEventCommand DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.beverly.hills.money.gang.proto.PushGameEventCommand();
  }

  public static com.beverly.hills.money.gang.proto.PushGameEventCommand getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PushGameEventCommand>
      PARSER = new com.google.protobuf.AbstractParser<PushGameEventCommand>() {
    @java.lang.Override
    public PushGameEventCommand parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<PushGameEventCommand> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PushGameEventCommand> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.beverly.hills.money.gang.proto.PushGameEventCommand getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

