// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/proto/server-events.proto

// Protobuf Java Version: 3.25.0
package com.beverly.hills.money.gang.proto;

public interface ServerEventsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:daikombat.dto.ServerEvents)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int64 eventId = 1;</code>
   * @return Whether the eventId field is set.
   */
  boolean hasEventId();
  /**
   * <code>optional int64 eventId = 1;</code>
   * @return The eventId.
   */
  long getEventId();

  /**
   * <code>optional int32 playersOnline = 2;</code>
   * @return Whether the playersOnline field is set.
   */
  boolean hasPlayersOnline();
  /**
   * <code>optional int32 playersOnline = 2;</code>
   * @return The playersOnline.
   */
  int getPlayersOnline();

  /**
   * <code>optional .daikombat.dto.ServerEvents.Error error = 3;</code>
   * @return Whether the error field is set.
   */
  boolean hasError();
  /**
   * <code>optional .daikombat.dto.ServerEvents.Error error = 3;</code>
   * @return The error.
   */
  com.beverly.hills.money.gang.proto.ServerEvents.Error getError();
  /**
   * <code>optional .daikombat.dto.ServerEvents.Error error = 3;</code>
   */
  com.beverly.hills.money.gang.proto.ServerEvents.ErrorOrBuilder getErrorOrBuilder();

  /**
   * <code>.daikombat.dto.ServerEvents.ChatEvent chatEvents = 4;</code>
   * @return Whether the chatEvents field is set.
   */
  boolean hasChatEvents();
  /**
   * <code>.daikombat.dto.ServerEvents.ChatEvent chatEvents = 4;</code>
   * @return The chatEvents.
   */
  com.beverly.hills.money.gang.proto.ServerEvents.ChatEvent getChatEvents();
  /**
   * <code>.daikombat.dto.ServerEvents.ChatEvent chatEvents = 4;</code>
   */
  com.beverly.hills.money.gang.proto.ServerEvents.ChatEventOrBuilder getChatEventsOrBuilder();

  /**
   * <code>.daikombat.dto.ServerEvents.GameEvents gameEvents = 5;</code>
   * @return Whether the gameEvents field is set.
   */
  boolean hasGameEvents();
  /**
   * <code>.daikombat.dto.ServerEvents.GameEvents gameEvents = 5;</code>
   * @return The gameEvents.
   */
  com.beverly.hills.money.gang.proto.ServerEvents.GameEvents getGameEvents();
  /**
   * <code>.daikombat.dto.ServerEvents.GameEvents gameEvents = 5;</code>
   */
  com.beverly.hills.money.gang.proto.ServerEvents.GameEventsOrBuilder getGameEventsOrBuilder();

  com.beverly.hills.money.gang.proto.ServerEvents.EventsCase getEventsCase();
}
