// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/proto/server-commands.proto

// Protobuf Java Version: 3.25.0
package com.beverly.hills.money.gang.proto;

public final class ServerCommands {
  private ServerCommands() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_daikombat_dto_ServerCommand_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_daikombat_dto_ServerCommand_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_daikombat_dto_PushChatEventCommand_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_daikombat_dto_PushChatEventCommand_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_daikombat_dto_JoinGameCommand_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_daikombat_dto_JoinGameCommand_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_daikombat_dto_PushGameEventCommand_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_daikombat_dto_PushGameEventCommand_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_daikombat_dto_PushGameEventCommand_Vector_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_daikombat_dto_PushGameEventCommand_Vector_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n.src/main/resources/proto/server-comman" +
      "ds.proto\022\rdaikombat.dto\"\371\001\n\rServerComman" +
      "d\022\016\n\006gameId\030\001 \001(\005\022\021\n\004hmac\030\002 \001(\014H\001\210\001\001\022:\n\013" +
      "chatCommand\030\004 \001(\0132#.daikombat.dto.PushCh" +
      "atEventCommandH\000\022:\n\013gameCommand\030\005 \001(\0132#." +
      "daikombat.dto.PushGameEventCommandH\000\0229\n\017" +
      "joinGameCommand\030\006 \001(\0132\036.daikombat.dto.Jo" +
      "inGameCommandH\000B\t\n\007commandB\007\n\005_hmac\"\'\n\024P" +
      "ushChatEventCommand\022\017\n\007message\030\001 \001(\t\"%\n\017" +
      "JoinGameCommand\022\022\n\nplayerName\030\001 \001(\t\"\237\002\n\024" +
      "PushGameEventCommand\022D\n\teventType\030\001 \001(\0162" +
      "1.daikombat.dto.PushGameEventCommand.Gam" +
      "eEventType\022<\n\010position\030\002 \001(\0132*.daikombat" +
      ".dto.PushGameEventCommand.Vector\022=\n\tdire" +
      "ction\030\003 \001(\0132*.daikombat.dto.PushGameEven" +
      "tCommand.Vector\032\036\n\006Vector\022\t\n\001x\030\001 \001(\002\022\t\n\001" +
      "y\030\002 \001(\002\"$\n\rGameEventType\022\010\n\004MOVE\020\000\022\t\n\005SH" +
      "OOT\020\001B&\n\"com.beverly.hills.money.gang.pr" +
      "otoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_daikombat_dto_ServerCommand_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_daikombat_dto_ServerCommand_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_daikombat_dto_ServerCommand_descriptor,
        new java.lang.String[] { "GameId", "Hmac", "ChatCommand", "GameCommand", "JoinGameCommand", "Command", });
    internal_static_daikombat_dto_PushChatEventCommand_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_daikombat_dto_PushChatEventCommand_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_daikombat_dto_PushChatEventCommand_descriptor,
        new java.lang.String[] { "Message", });
    internal_static_daikombat_dto_JoinGameCommand_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_daikombat_dto_JoinGameCommand_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_daikombat_dto_JoinGameCommand_descriptor,
        new java.lang.String[] { "PlayerName", });
    internal_static_daikombat_dto_PushGameEventCommand_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_daikombat_dto_PushGameEventCommand_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_daikombat_dto_PushGameEventCommand_descriptor,
        new java.lang.String[] { "EventType", "Position", "Direction", });
    internal_static_daikombat_dto_PushGameEventCommand_Vector_descriptor =
      internal_static_daikombat_dto_PushGameEventCommand_descriptor.getNestedTypes().get(0);
    internal_static_daikombat_dto_PushGameEventCommand_Vector_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_daikombat_dto_PushGameEventCommand_Vector_descriptor,
        new java.lang.String[] { "X", "Y", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
