// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/proto/server-status.proto

// Protobuf Java Version: 3.25.0
package com.beverly.hills.money.gang.proto;

/**
 * Protobuf type {@code daikombat.dto.ServerStatus}
 */
public final class ServerStatus extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:daikombat.dto.ServerStatus)
    ServerStatusOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ServerStatus.newBuilder() to construct.
  private ServerStatus(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ServerStatus() {
    gameIds_ = emptyIntList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ServerStatus();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.beverly.hills.money.gang.proto.ServerStatusOuterClass.internal_static_daikombat_dto_ServerStatus_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.beverly.hills.money.gang.proto.ServerStatusOuterClass.internal_static_daikombat_dto_ServerStatus_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.beverly.hills.money.gang.proto.ServerStatus.class, com.beverly.hills.money.gang.proto.ServerStatus.Builder.class);
  }

  public static final int SERVERID_FIELD_NUMBER = 1;
  private int serverId_ = 0;
  /**
   * <code>int32 serverId = 1;</code>
   * @return The serverId.
   */
  @java.lang.Override
  public int getServerId() {
    return serverId_;
  }

  public static final int GAMEIDS_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private com.google.protobuf.Internal.IntList gameIds_ =
      emptyIntList();
  /**
   * <code>repeated int32 gameIds = 2;</code>
   * @return A list containing the gameIds.
   */
  @java.lang.Override
  public java.util.List<java.lang.Integer>
      getGameIdsList() {
    return gameIds_;
  }
  /**
   * <code>repeated int32 gameIds = 2;</code>
   * @return The count of gameIds.
   */
  public int getGameIdsCount() {
    return gameIds_.size();
  }
  /**
   * <code>repeated int32 gameIds = 2;</code>
   * @param index The index of the element to return.
   * @return The gameIds at the given index.
   */
  public int getGameIds(int index) {
    return gameIds_.getInt(index);
  }
  private int gameIdsMemoizedSerializedSize = -1;

  public static final int REQUIRESPIN_FIELD_NUMBER = 3;
  private boolean requiresPin_ = false;
  /**
   * <code>bool requiresPin = 3;</code>
   * @return The requiresPin.
   */
  @java.lang.Override
  public boolean getRequiresPin() {
    return requiresPin_;
  }

  public static final int PLAYERSONLINE_FIELD_NUMBER = 4;
  private int playersOnline_ = 0;
  /**
   * <code>int32 playersOnline = 4;</code>
   * @return The playersOnline.
   */
  @java.lang.Override
  public int getPlayersOnline() {
    return playersOnline_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (serverId_ != 0) {
      output.writeInt32(1, serverId_);
    }
    if (getGameIdsList().size() > 0) {
      output.writeUInt32NoTag(18);
      output.writeUInt32NoTag(gameIdsMemoizedSerializedSize);
    }
    for (int i = 0; i < gameIds_.size(); i++) {
      output.writeInt32NoTag(gameIds_.getInt(i));
    }
    if (requiresPin_ != false) {
      output.writeBool(3, requiresPin_);
    }
    if (playersOnline_ != 0) {
      output.writeInt32(4, playersOnline_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (serverId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, serverId_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < gameIds_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeInt32SizeNoTag(gameIds_.getInt(i));
      }
      size += dataSize;
      if (!getGameIdsList().isEmpty()) {
        size += 1;
        size += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(dataSize);
      }
      gameIdsMemoizedSerializedSize = dataSize;
    }
    if (requiresPin_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(3, requiresPin_);
    }
    if (playersOnline_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, playersOnline_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.beverly.hills.money.gang.proto.ServerStatus)) {
      return super.equals(obj);
    }
    com.beverly.hills.money.gang.proto.ServerStatus other = (com.beverly.hills.money.gang.proto.ServerStatus) obj;

    if (getServerId()
        != other.getServerId()) return false;
    if (!getGameIdsList()
        .equals(other.getGameIdsList())) return false;
    if (getRequiresPin()
        != other.getRequiresPin()) return false;
    if (getPlayersOnline()
        != other.getPlayersOnline()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SERVERID_FIELD_NUMBER;
    hash = (53 * hash) + getServerId();
    if (getGameIdsCount() > 0) {
      hash = (37 * hash) + GAMEIDS_FIELD_NUMBER;
      hash = (53 * hash) + getGameIdsList().hashCode();
    }
    hash = (37 * hash) + REQUIRESPIN_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getRequiresPin());
    hash = (37 * hash) + PLAYERSONLINE_FIELD_NUMBER;
    hash = (53 * hash) + getPlayersOnline();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.beverly.hills.money.gang.proto.ServerStatus parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.beverly.hills.money.gang.proto.ServerStatus parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.beverly.hills.money.gang.proto.ServerStatus parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.beverly.hills.money.gang.proto.ServerStatus parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.beverly.hills.money.gang.proto.ServerStatus parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.beverly.hills.money.gang.proto.ServerStatus parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.beverly.hills.money.gang.proto.ServerStatus parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.beverly.hills.money.gang.proto.ServerStatus parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.beverly.hills.money.gang.proto.ServerStatus parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.beverly.hills.money.gang.proto.ServerStatus parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.beverly.hills.money.gang.proto.ServerStatus parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.beverly.hills.money.gang.proto.ServerStatus parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.beverly.hills.money.gang.proto.ServerStatus prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code daikombat.dto.ServerStatus}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:daikombat.dto.ServerStatus)
      com.beverly.hills.money.gang.proto.ServerStatusOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.beverly.hills.money.gang.proto.ServerStatusOuterClass.internal_static_daikombat_dto_ServerStatus_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.beverly.hills.money.gang.proto.ServerStatusOuterClass.internal_static_daikombat_dto_ServerStatus_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.beverly.hills.money.gang.proto.ServerStatus.class, com.beverly.hills.money.gang.proto.ServerStatus.Builder.class);
    }

    // Construct using com.beverly.hills.money.gang.proto.ServerStatus.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      serverId_ = 0;
      gameIds_ = emptyIntList();
      requiresPin_ = false;
      playersOnline_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.beverly.hills.money.gang.proto.ServerStatusOuterClass.internal_static_daikombat_dto_ServerStatus_descriptor;
    }

    @java.lang.Override
    public com.beverly.hills.money.gang.proto.ServerStatus getDefaultInstanceForType() {
      return com.beverly.hills.money.gang.proto.ServerStatus.getDefaultInstance();
    }

    @java.lang.Override
    public com.beverly.hills.money.gang.proto.ServerStatus build() {
      com.beverly.hills.money.gang.proto.ServerStatus result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.beverly.hills.money.gang.proto.ServerStatus buildPartial() {
      com.beverly.hills.money.gang.proto.ServerStatus result = new com.beverly.hills.money.gang.proto.ServerStatus(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.beverly.hills.money.gang.proto.ServerStatus result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.serverId_ = serverId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        gameIds_.makeImmutable();
        result.gameIds_ = gameIds_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.requiresPin_ = requiresPin_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.playersOnline_ = playersOnline_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.beverly.hills.money.gang.proto.ServerStatus) {
        return mergeFrom((com.beverly.hills.money.gang.proto.ServerStatus)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.beverly.hills.money.gang.proto.ServerStatus other) {
      if (other == com.beverly.hills.money.gang.proto.ServerStatus.getDefaultInstance()) return this;
      if (other.getServerId() != 0) {
        setServerId(other.getServerId());
      }
      if (!other.gameIds_.isEmpty()) {
        if (gameIds_.isEmpty()) {
          gameIds_ = other.gameIds_;
          gameIds_.makeImmutable();
          bitField0_ |= 0x00000002;
        } else {
          ensureGameIdsIsMutable();
          gameIds_.addAll(other.gameIds_);
        }
        onChanged();
      }
      if (other.getRequiresPin() != false) {
        setRequiresPin(other.getRequiresPin());
      }
      if (other.getPlayersOnline() != 0) {
        setPlayersOnline(other.getPlayersOnline());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              serverId_ = input.readInt32();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              int v = input.readInt32();
              ensureGameIdsIsMutable();
              gameIds_.addInt(v);
              break;
            } // case 16
            case 18: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              ensureGameIdsIsMutable();
              while (input.getBytesUntilLimit() > 0) {
                gameIds_.addInt(input.readInt32());
              }
              input.popLimit(limit);
              break;
            } // case 18
            case 24: {
              requiresPin_ = input.readBool();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 32: {
              playersOnline_ = input.readInt32();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int serverId_ ;
    /**
     * <code>int32 serverId = 1;</code>
     * @return The serverId.
     */
    @java.lang.Override
    public int getServerId() {
      return serverId_;
    }
    /**
     * <code>int32 serverId = 1;</code>
     * @param value The serverId to set.
     * @return This builder for chaining.
     */
    public Builder setServerId(int value) {

      serverId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>int32 serverId = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearServerId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      serverId_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.Internal.IntList gameIds_ = emptyIntList();
    private void ensureGameIdsIsMutable() {
      if (!gameIds_.isModifiable()) {
        gameIds_ = makeMutableCopy(gameIds_);
      }
      bitField0_ |= 0x00000002;
    }
    /**
     * <code>repeated int32 gameIds = 2;</code>
     * @return A list containing the gameIds.
     */
    public java.util.List<java.lang.Integer>
        getGameIdsList() {
      gameIds_.makeImmutable();
      return gameIds_;
    }
    /**
     * <code>repeated int32 gameIds = 2;</code>
     * @return The count of gameIds.
     */
    public int getGameIdsCount() {
      return gameIds_.size();
    }
    /**
     * <code>repeated int32 gameIds = 2;</code>
     * @param index The index of the element to return.
     * @return The gameIds at the given index.
     */
    public int getGameIds(int index) {
      return gameIds_.getInt(index);
    }
    /**
     * <code>repeated int32 gameIds = 2;</code>
     * @param index The index to set the value at.
     * @param value The gameIds to set.
     * @return This builder for chaining.
     */
    public Builder setGameIds(
        int index, int value) {

      ensureGameIdsIsMutable();
      gameIds_.setInt(index, value);
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>repeated int32 gameIds = 2;</code>
     * @param value The gameIds to add.
     * @return This builder for chaining.
     */
    public Builder addGameIds(int value) {

      ensureGameIdsIsMutable();
      gameIds_.addInt(value);
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>repeated int32 gameIds = 2;</code>
     * @param values The gameIds to add.
     * @return This builder for chaining.
     */
    public Builder addAllGameIds(
        java.lang.Iterable<? extends java.lang.Integer> values) {
      ensureGameIdsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, gameIds_);
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>repeated int32 gameIds = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearGameIds() {
      gameIds_ = emptyIntList();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }

    private boolean requiresPin_ ;
    /**
     * <code>bool requiresPin = 3;</code>
     * @return The requiresPin.
     */
    @java.lang.Override
    public boolean getRequiresPin() {
      return requiresPin_;
    }
    /**
     * <code>bool requiresPin = 3;</code>
     * @param value The requiresPin to set.
     * @return This builder for chaining.
     */
    public Builder setRequiresPin(boolean value) {

      requiresPin_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>bool requiresPin = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearRequiresPin() {
      bitField0_ = (bitField0_ & ~0x00000004);
      requiresPin_ = false;
      onChanged();
      return this;
    }

    private int playersOnline_ ;
    /**
     * <code>int32 playersOnline = 4;</code>
     * @return The playersOnline.
     */
    @java.lang.Override
    public int getPlayersOnline() {
      return playersOnline_;
    }
    /**
     * <code>int32 playersOnline = 4;</code>
     * @param value The playersOnline to set.
     * @return This builder for chaining.
     */
    public Builder setPlayersOnline(int value) {

      playersOnline_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>int32 playersOnline = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearPlayersOnline() {
      bitField0_ = (bitField0_ & ~0x00000008);
      playersOnline_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:daikombat.dto.ServerStatus)
  }

  // @@protoc_insertion_point(class_scope:daikombat.dto.ServerStatus)
  private static final com.beverly.hills.money.gang.proto.ServerStatus DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.beverly.hills.money.gang.proto.ServerStatus();
  }

  public static com.beverly.hills.money.gang.proto.ServerStatus getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ServerStatus>
      PARSER = new com.google.protobuf.AbstractParser<ServerStatus>() {
    @java.lang.Override
    public ServerStatus parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ServerStatus> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ServerStatus> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.beverly.hills.money.gang.proto.ServerStatus getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

