// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/proto/server-status.proto

// Protobuf Java Version: 3.25.0
package com.beverly.hills.money.gang.proto;

public final class ServerStatusOuterClass {
  private ServerStatusOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_daikombat_dto_ServerStatus_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_daikombat_dto_ServerStatus_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n,src/main/resources/proto/server-status" +
      ".proto\022\rdaikombat.dto\"]\n\014ServerStatus\022\020\n" +
      "\010serverId\030\001 \001(\005\022\017\n\007gameIds\030\002 \003(\005\022\023\n\013requ" +
      "iresPin\030\003 \001(\010\022\025\n\rplayersOnline\030\004 \001(\005B&\n\"" +
      "com.beverly.hills.money.gang.protoP\001b\006pr" +
      "oto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_daikombat_dto_ServerStatus_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_daikombat_dto_ServerStatus_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_daikombat_dto_ServerStatus_descriptor,
        new java.lang.String[] { "ServerId", "GameIds", "RequiresPin", "PlayersOnline", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
