// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/proto/server-events.proto

// Protobuf Java Version: 3.25.0
package com.beverly.hills.money.gang.proto;

public final class ServerEventsOuterClass {
  private ServerEventsOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_daikombat_dto_ServerEvents_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_daikombat_dto_ServerEvents_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_daikombat_dto_ServerEvents_Error_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_daikombat_dto_ServerEvents_Error_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_daikombat_dto_ServerEvents_ChatEvents_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_daikombat_dto_ServerEvents_ChatEvents_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_daikombat_dto_ServerEvents_GameEvents_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_daikombat_dto_ServerEvents_GameEvents_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_daikombat_dto_ServerEvents_ChatEvent_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_daikombat_dto_ServerEvents_ChatEvent_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_daikombat_dto_ServerEvents_GameEvent_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_daikombat_dto_ServerEvents_GameEvent_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_daikombat_dto_ServerEvents_GameEventPlayerStats_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_daikombat_dto_ServerEvents_GameEventPlayerStats_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_daikombat_dto_ServerEvents_Vector_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_daikombat_dto_ServerEvents_Vector_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n,src/main/resources/proto/server-events" +
      ".proto\022\rdaikombat.dto\"\321\010\n\014ServerEvents\022\024" +
      "\n\007eventId\030\001 \001(\003H\001\210\001\001\022\032\n\rplayersOnline\030\002 " +
      "\001(\005H\002\210\001\001\0225\n\005error\030\003 \001(\0132!.daikombat.dto." +
      "ServerEvents.ErrorH\003\210\001\001\022;\n\nchatEvents\030\004 " +
      "\001(\0132%.daikombat.dto.ServerEvents.ChatEve" +
      "ntH\000\022<\n\ngameEvents\030\005 \001(\0132&.daikombat.dto" +
      ".ServerEvents.GameEventsH\000\032+\n\005Error\022\021\n\te" +
      "rrorCode\030\001 \001(\005\022\017\n\007message\030\002 \001(\t\032C\n\nChatE" +
      "vents\0225\n\006events\030\001 \003(\0132%.daikombat.dto.Se" +
      "rverEvents.ChatEvent\032C\n\nGameEvents\0225\n\006ev" +
      "ents\030\001 \003(\0132%.daikombat.dto.ServerEvents." +
      "GameEvent\0320\n\tChatEvent\022\022\n\nplayerName\030\001 \001" +
      "(\t\022\017\n\007message\030\002 \001(\t\032\321\002\n\tGameEvent\022@\n\006pla" +
      "yer\030\001 \001(\01320.daikombat.dto.ServerEvents.G" +
      "ameEventPlayerStats\022M\n\016affectedPlayer\030\002 " +
      "\001(\01320.daikombat.dto.ServerEvents.GameEve" +
      "ntPlayerStatsH\000\210\001\001\022F\n\teventType\030\003 \001(\01623." +
      "daikombat.dto.ServerEvents.GameEvent.Gam" +
      "eEventType\"X\n\rGameEventType\022\010\n\004MOVE\020\000\022\t\n" +
      "\005SHOOT\020\001\022\014\n\010GET_SHOT\020\002\022\t\n\005DEATH\020\003\022\t\n\005SPA" +
      "WN\020\004\022\016\n\nDISCONNECT\020\005B\021\n\017_affectedPlayer\032" +
      "\315\001\n\024GameEventPlayerStats\022\020\n\010playerId\030\001 \001" +
      "(\005\022\027\n\nplayerName\030\002 \001(\tH\000\210\001\001\0224\n\010position\030" +
      "\003 \001(\0132\".daikombat.dto.ServerEvents.Vecto" +
      "r\0225\n\tdirection\030\004 \001(\0132\".daikombat.dto.Ser" +
      "verEvents.Vector\022\016\n\006health\030\005 \001(\005B\r\n\013_pla" +
      "yerName\032\036\n\006Vector\022\t\n\001x\030\001 \001(\002\022\t\n\001y\030\002 \001(\002B" +
      "\010\n\006eventsB\n\n\010_eventIdB\020\n\016_playersOnlineB" +
      "\010\n\006_errorB&\n\"com.beverly.hills.money.gan" +
      "g.protoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_daikombat_dto_ServerEvents_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_daikombat_dto_ServerEvents_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_daikombat_dto_ServerEvents_descriptor,
        new java.lang.String[] { "EventId", "PlayersOnline", "Error", "ChatEvents", "GameEvents", "Events", });
    internal_static_daikombat_dto_ServerEvents_Error_descriptor =
      internal_static_daikombat_dto_ServerEvents_descriptor.getNestedTypes().get(0);
    internal_static_daikombat_dto_ServerEvents_Error_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_daikombat_dto_ServerEvents_Error_descriptor,
        new java.lang.String[] { "ErrorCode", "Message", });
    internal_static_daikombat_dto_ServerEvents_ChatEvents_descriptor =
      internal_static_daikombat_dto_ServerEvents_descriptor.getNestedTypes().get(1);
    internal_static_daikombat_dto_ServerEvents_ChatEvents_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_daikombat_dto_ServerEvents_ChatEvents_descriptor,
        new java.lang.String[] { "Events", });
    internal_static_daikombat_dto_ServerEvents_GameEvents_descriptor =
      internal_static_daikombat_dto_ServerEvents_descriptor.getNestedTypes().get(2);
    internal_static_daikombat_dto_ServerEvents_GameEvents_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_daikombat_dto_ServerEvents_GameEvents_descriptor,
        new java.lang.String[] { "Events", });
    internal_static_daikombat_dto_ServerEvents_ChatEvent_descriptor =
      internal_static_daikombat_dto_ServerEvents_descriptor.getNestedTypes().get(3);
    internal_static_daikombat_dto_ServerEvents_ChatEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_daikombat_dto_ServerEvents_ChatEvent_descriptor,
        new java.lang.String[] { "PlayerName", "Message", });
    internal_static_daikombat_dto_ServerEvents_GameEvent_descriptor =
      internal_static_daikombat_dto_ServerEvents_descriptor.getNestedTypes().get(4);
    internal_static_daikombat_dto_ServerEvents_GameEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_daikombat_dto_ServerEvents_GameEvent_descriptor,
        new java.lang.String[] { "Player", "AffectedPlayer", "EventType", });
    internal_static_daikombat_dto_ServerEvents_GameEventPlayerStats_descriptor =
      internal_static_daikombat_dto_ServerEvents_descriptor.getNestedTypes().get(5);
    internal_static_daikombat_dto_ServerEvents_GameEventPlayerStats_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_daikombat_dto_ServerEvents_GameEventPlayerStats_descriptor,
        new java.lang.String[] { "PlayerId", "PlayerName", "Position", "Direction", "Health", });
    internal_static_daikombat_dto_ServerEvents_Vector_descriptor =
      internal_static_daikombat_dto_ServerEvents_descriptor.getNestedTypes().get(6);
    internal_static_daikombat_dto_ServerEvents_Vector_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_daikombat_dto_ServerEvents_Vector_descriptor,
        new java.lang.String[] { "X", "Y", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
